### PR TITLE
Pre-Merge PR Checks for Diagnostics Plugin

### PR DESCRIPTION
**Pull request by davidvonthenen**
## What this PR does / why we need it

This does the same thing as the e2e test on main... except this checks to make sure that PRs submitted against the diagnostics plugin will pass the tests before getting merged into main. If the test fails, merging will be blocked until the issue is addressed.

The `e2e-test.sh` was broken out into: 
- `setup-e2e-test.sh` which handles setting things for the e2e test
- reworked the `e2e-test.sh` which now only performs the checks/tests without setup so we can run against latest TF

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Pre-Merge PR Checks for Diagnostics Plugin
```

## Which issue(s) this PR fixes

NA

## Describe testing done for PR

NA

## Special notes for your reviewer

NA

### CODE REVIEW

**Review by vladimirvivien — DISMISSED** [review]
LGTM

**Review by karuppiah7890 — DISMISSED** [review]
LGTM!

**Comment by dvonthenen** [comment]
This is ready for review... the PR check is passing here:
https://github.com/vmware-tanzu/community-edition/runs/4142852334?check_suite_focus=true

**Review by vladimirvivien — APPROVED** [review]
LGTM

**Review by nrb — APPROVED** [review]

**Pull request merged**
