### PR TITLE
urllint: linter for http and https links/urls

### PR DESCRIPTION
**Pull request by JitenPalaparthi**
## What this PR does / why we need it

This PR is an  url  linter checks whether a strict url is valid or not.
## Which issue(s) this PR fixes

Fixes: # [One of the items](https://github.com/vmware-tanzu/tce/issues/1173)

## Describe testing done for PR

tested in local environment. Go to root directory of  Community Edition and run the below command
```make urllint ```
## Does this PR introduce a user-facing change?
No

```release-note
Not Applicable
```

### CODE REVIEW

**Review by navidshaikh — CHANGES_REQUESTED** [review]
thanks!

- please rename linturl --> urllint (to align with other linters)
- remove the binary file from the PR
- update the config path and name
- wire this linter Makefile 'check' target
- retitle the PR

**Review by navidshaikh — CHANGES_REQUESTED** [review]

**Review by stmcginnis — CHANGES_REQUESTED** [review]
Please squash your commits and provide a detailed commit message.

**Review by navidshaikh — DISMISSED** [review]
commits are now squashed!

**Review by navidshaikh — CHANGES_REQUESTED** [review]

**Review by stmcginnis — APPROVED** [review]
Looks like all comments have been addressed, and runs fine locally for me.

**Pull request merged**
