### PR TITLE
imagelinter to check images are Alpine based or not

### LINKED ISSUE #1173: Lint checks for TCE
This is a placeholder issue to discuss and capture what kind of Lint checks we are doing and also the ones we aren't doing but want to do

To define the scope / code that's going to be linted, possible scope I can think of right now is
- Golang code
- Shell scripts - mostly bash scripts
- Markdown files - internal docs and docs website source files
- CI/CD config - GitHub Actions workflow config

We can also look at the different kind of files TCE has, using [tokei](https://github.com/XAMPPRocky/tokei) the codebase info is -

```bash
$ tokei
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 Batch                   1           36           17           11            8
 Go                     20         1855         1413          101          341
 JavaScript              1          123           92           10           21
 Makefile                2          398          253           61           84
 Sass                    7         1430         1341           22           67
 Shell                  24         1366          889          237          240
 SVG                  1132         5954         5953            1            0
 Plain Text              6          320            0          308           12
 TOML                    1           30           22            0            8
 YAML                  475       102980        95952         5784         1244
-------------------------------------------------------------------------------
 HTML                   34          774          742            0           32
 |- JavaScript           1            7            7            0            0
 (Total)                            781          749            0           32
-------------------------------------------------------------------------------
 Markdown              182        11174            0         7990         3184
 |- BASH                10          131          130            0            1
 |- INI                  1            4            4            0            0
 |- JSON                 2           48           48            0            0
 |- Shell               24          404          377            6           21
 |- YAML                14         1072          861          172           39
 (Total)                          12833         1420         8168         3245
===============================================================================
 Total                1885       126440       106674        14525         5241
===============================================================================
```

Reasoning
- The default reasoning for linting applies - both code format / style and code standards needs to be good for a consistent experience while reading and grokking code
- Avoid small and simple issues early on with automated linters

Tools that we are already using
- [shellcheck](https://github.com/koalaman/shellcheck) - for linting bash scripts
- [golangci-lint](https://github.com/golangci/golangci-lint/) - for linting golang files with various linting tools under this one tool. List of linters under it - https://golangci-lint.run/usage/linters/
- mdlint - for linting markdown files - we get the tool from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/hack/tools/mdlint/Dockerfile - https://www.npmjs.com/package/markdownlint-cli

Related files
- https://github.com/vmware-tanzu/tce/blob/main/hack/check-mdlint.sh , https://github.com/vmware-tanzu/tce/blob/main/.github/workflows/check-mdlint.yaml
- https://github.com/vmware-tanzu/tce/blob/main/hack/check-shell.sh , https://github.com/vmware-tanzu/tce/blob/main/.github/workflows/check-shell.yaml
- https://github.com/vmware-tanzu/tce/blob/main/.golangci.yaml , https://github.com/vmware-tanzu/tce/blob/main/.github/workflows/check-lint.yaml

### PR DESCRIPTION
**Pull request by JitenPalaparthi**
## What this PR does / why we need it

This PR is an  image linter check whether image is used in dockerfile , kubernetes yaml or yml file is not Alpine based image.
## Which issue(s) this PR fixes

Fixes: [One of the items](https://github.com/vmware-tanzu/tce/issues/1173)

## Describe testing done for PR

tested in local environment. Go to root directory of  Community Edition and run the below command
```make imagelint ```
## Does this PR introduce a user-facing change?
No

```release-note
Not Applicable
```

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
I'm not sure this approach makes sense to me, but I'm open to hearing feedback.

With the carvel set of tooling, when we want to replace an image from the upstream manifest, we can either provide an overlay or a kbld replace. Both end up resulting in an `.imgpkg/images.yaml` file that has _both_ the images present (since imgpkg still needs to resolve what is getting replaced from the upstream)

But, the bundle that ends up getting installed is the one that has the overlayed image, not the original one.

For example, look at the `local-path-storage` PR which replaces the upstream manifest's `image` field with the one that is built by us: https://github.com/vmware-tanzu/community-edition/pull/1603

The `image.yaml` file has _both_ the files:
```yaml
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: busybox
  image: index.docker.io/library/busybox@sha256:b5fc1d7b2e4ea86a06b0cf88de915a2c43a99a00b6b3c0af731e5f4c07ae8eff
- annotations:
    kbld.carvel.dev/id: projects.registry.vmware.com/tce/local-path-storage:0.0.19
  image: projects.registry.vmware.com/tce/local-path-storage@sha256:a2d213121067f0f3df26ec813eb752b4e4d5e9f590b51d0a922c4ecd71541d65
- annotations:
    kbld.carvel.dev/id: rancher/local-path-provisioner:v0.0.19
  image: index.docker.io/rancher/local-path-provisioner@sha256:9666b1635fec95d4e2251661e135c90678b8f45fd0f8324c55db99c80e2a958c
```

I'm guessing this will still cause the linter to fail since we are resolving the original image.

The only solution I see for this is to create a long list of `ignoreImages` for the various versions that we end up shipping (which it looks like we've already started in this PR)

Instead, I think a better approach may be to look into the actual bundle yaml that ends up getting built by `ytt`. Using the `local-path-storage` example from the PR above, the deployment yaml ends up looking like:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: tanzu-local-path-storage
  ...
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
      - name: local-path-provisioner
        image: projects.registry.vmware.com/tce/local-path-provisioner:0.0.20
        imagePullPolicy: IfNotPresent
```
Note that we are _not_ using the default upstream image, but the one that gets replaced.

**Review by davidvonthenen — COMMENTED** [review]
This is going to be pretty value for current needs and future package contributions! Awesome work!

**Review by davidvonthenen — COMMENTED** [review]
A couple of more places where we are referencing the personal repo

**Review by jpmcb — APPROVED** [review]
This is fine to and I will create a followup issue to address the `imagelint` program looking into the `kbld` output for bundles and not just the arbitrary `image` fields in yaml

**Pull request merged**
