### PR TITLE
Explicity ignore file end with [568vq].

### PR DESCRIPTION
**Pull request by lubronzhan**
## What this PR does / why we need it

It will block team to add packages with version like `*.5`

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #https://github.com/vmware-tanzu/community-edition/issues/2916

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
I believe the `$` will glob for a literal dollar sign, not the end of the string:

Screen Shot 2022-01-24 at 11 32 51 AM

And this seems to also not be working in the gitignore:
```
$ echo "hello world" > test.q
$ git status
...
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        test.q

```

Again, I'm wondering if we just remove those two lines. Not sure what they are for

**Comment by lubronzhan** [comment]
Thanks for finding the issue.
I think these are for cgo's output after I did some googling. Not many repos has these lines. Even k8s repo

**Comment by lubronzhan** [comment]
Ok this can work
```
!*.[568vq]/
```
image

**Comment by stmcginnis** [comment]
> I'm wondering if we can just remove both those lines since I'm really not sure what they do for us

I think so, and that would be my preference.

If these are for cgo, I think that's OK. We don't really support cgo (at least officially so far) so I don't think we need to do anything special to accomodate that.

**Comment by lubronzhan** [comment]
Ok I just removed these two lines.

**Review by jpmcb — APPROVED** [review]

**Comment by stmcginnis** [comment]
Thanks!

**Pull request merged**
