### PR TITLE
Grafana addon e2e tests

### PR DESCRIPTION
**Pull request by JitenPalaparthi**
## What this PR does / why we need it

 Contains  e2e tests for Grafana addon along with few helper methods. All below mentioned steps are automated.
 In order to test Grafana , the below manual steps are to be performed.The same steps are used for automation by using go Ginkgo framework.

 - Step-1 ```tanzu package install grafana.tce.vmware.com ``` 
 - Step-2 Make sure that the deployment is ready to serve before going to run tests.
   ``` kubectl get deployment -l app.kubernetes.io/name=grafana -n grafana-addon -o jsonpath={..status.conditions[?(@.type=="Available")].status} ```
 - Step-3 once everything is up and running , the actual tests will do two things.
     -  port forward : ```kubectl port-forward   deployment.apps/grafana -n grafana-addon   56016:3000 ```
     -  check the health of grafana api: ```crul -I http://127.0.0.1:56016/api/health``` .But this step is done in the tests using core golang http pacakge.
     - If the status is 200, that means grafana is up and running. 
- Step-4 : after tests are run , suite will delete grafana package ``` tanzu package delete grafana.tce.vmware.com``` 
## Which issue(s) this PR fixes

Fixes: # [1092](https://github.com/vmware-tanzu/tce/issues/1092)
## Describe testing done for PR

Tests done on Standalone cluster using ginkgo
- cd to the pacakge path i.e addons/packages/grafana/test/e2e
- ``` ginkgo -v ``` 
## Special notes for your reviewer

N/A
## Does this PR introduce a user-facing change?

N/A
```release-note

```

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
Awesome! Thanks for adding these tests. We need a few additional things:

- A readme in the testing folder describing what the tests do and how to run the tests
- A go module at the root of the testing folder. Since we removed the top-level go module in #735, each individual go "program" will need to be it's own go module. Please rebase this PR ontop of `main` and add a go.mod and go.sum file

Reference PR for how external-dns did this: https://github.com/vmware-tanzu/tce/pull/753

**Review by jpmcb — CHANGES_REQUESTED** [review]
Please make similar changes as requested in: https://github.com/vmware-tanzu/tce/pull/1068

- There should _not_ be a top level `test/pkg/` go module. This should be replaced with the module located at `addon/packages/test/pkg`
- The testing module should _not_ be nested in `e2e/` but should be one level down in `addons/packages/{pacakge-name}/test`. The e2e tests can then exist as a go package inside that higher level module.
- Similarly, the readme makes more sense in the same directly as the go mod and not one level up in `e2e/`

Please reference how this is done in external-dns as this is the model we are approaching testing with: https://github.com/vmware-tanzu/tce/tree/main/addons/packages/external-dns/test

**Review by jpmcb — CHANGES_REQUESTED** [review]
Please note recent requirements regarding a default `makefile` (and subsequent make targets) for all go modules. This is the cause of the following linting error:
```
-- Getting deps for ./addons/packages/grafana/test --
make[1]: *** No rule to make target 'get-deps'.  Stop.
```

Reference the [`CONTRIBUTING.md` file](https://github.com/vmware-tanzu/community-edition/blob/main/CONTRIBUTING.md#nested-makefiles) regarding expectations for go modules in the TCE project.

The external [DNS package is also a good resource](https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/external-dns/test) for an up to date go module

**Review by jpmcb — CHANGES_REQUESTED** [review]

**Review by jpmcb — CHANGES_REQUESTED** [review]
Per the contributing guidelines, each go module needs it's own makefile with expected targets. Please add a makefile per the requirements: https://github.com/vmware-tanzu/community-edition/blob/main/CONTRIBUTING.md#nested-makefiles

**Review by jpmcb — CHANGES_REQUESTED** [review]
There are linting errors (which the linter wasn't reporting - see #1566 for details). Please fix the linting errors

Otherwise, from a Go module structure perspective, this is looking good!

Let's get @vmware-tanzu/pkg-grafana-owners in here to take a look and approve

**Review by akodali18 — APPROVED** [review]
Only one question about the structure: 
@jpmcb : It looks like test package structure in TCE is to include the package version "addons/packages/{package-name}/{package-version}/test" based on the example test here https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/external-dns/0.8.0/test

I can see why we want version specific tests, but can also see the need for global tests which could be put outside the versioned directory at "addons/packages/{package-name}/test". Any thoughts ?

Other than that change lgtm.

**Pull request closed without merging**
