### PR TITLE
Implements meaningful exit codes for create `unmanaged` cluster

### LINKED ISSUE #3025: Proposal: Provide meaningful exit error codes for `unmanaged-cluster`
## Feature Request
When executing the plugin from within a script it is almost impossible to know what is the reason of a failure without parsing the output file and processing it. It'll be ideal that every error would provide a different error exit code (!=0) and that these are documented so that embedding "unmanaged-cluster" functionality in other tools can be easier.

### PR DESCRIPTION
**Pull request by jpmcb**
## What this PR does / why we need it
As outlined in https://github.com/vmware-tanzu/community-edition/pull/3072

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
Adds meaningful exit codes to unmanaged cluster create
```

## Describe testing done for PR
Build binaries and runs as expected

### CODE REVIEW

**Comment by jpmcb** [comment]
Marking as draft until proposal is accepted and merged

**Comment by joshrosso** [comment]
@jpmcb approved https://github.com/vmware-tanzu/community-edition/issues/3025

Does that make this PR ready for review?

**Comment by jpmcb** [comment]
@joshrosso ready to rock and roll!

**Comment by jorgemoralespou** [comment]
@jpmcb How are exit codes from the Kind cluster creation managed? currently the installer is exposing the "docker run" output error. I'm assuming it's providing exit code 7 (7:ErrCreateCluster - Unable to create new cluster ). But on the screen  [Docker run exit codes](https://docs.docker.com/engine/reference/run/#exit-status) is printed which might be misleading.

**Comment by jpmcb** [comment]
@jorgemoralespou - operating system exit codes and the error messages that gets displayed are not correlated and serve different "end users". The displayed error message is relevant for a human operator but carries little meaning to any kind of automation. On the inverse, exit codes likely aren't being inspected by a human operator but are hugely beneficial for an automated system.

So, for example, exit code `7` relates to some general error when creating a cluster during the `tanzu` package bootstrapping but does not attempt to inspect exactly _what_ that error is. It will simply display and return that error to the user on screen. Since the `tanzu` package may be plug & play with any number of different providers (like `kind` for example) we cannot attempt to parse and provide more granular exit codes; they are relevant to the bootstrapping process and general enough that they can apply to any provider.

I do not anticipate `docker` returning it's exit code in an error message to be confusing to human end users since they likely won't be inspecting the exit codes of the failing process; they are going to read the error message. Automated systems won't be reading those exit messages on screen, they will be inspecting our error codes.

**Review by davidvonthenen — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]
Looks good!

**Pull request merged**
