### PR TITLE
docs(README): Add github workflow CI badges

### PR DESCRIPTION
**Pull request by navidshaikh**
## What this PR does / why we need it
docs(README): Add github workflow CI badges
For following workflows:
- Build - Create Dev/Staging
- Check - Main (All tests)
- Check - imagelint
- E2E Test - vSphere Management Cluster
- E2E Test - vSphere Standalone Cluster
- E2E Test - Azure Management Cluster
- E2E Test - Azure Standalone Cluster
- E2E Test - AWS Management Cluster
- E2E Test - AWS Standalone Cluster

Signed-off-by: Navid Shaikh <navids@vmware.com>

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

image

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
Nice! Each of these look good to me. But I'm wondering if we could maybe put them _below_ the TCE logo, introduction, and GIF in the readme? This is what I see in the preview right now:

tce-badges

There's def some weird spacing since the TCE logo is left aligned.

**Comment by dvonthenen** [comment]
This is GREAT!!! Love it!

**Comment by navidshaikh** [comment]
Updated to list the status badges after GIF and recreated the status badges after workflow name renames https://github.com/vmware-tanzu/community-edition/pull/2576

**Review by davidvonthenen — APPROVED** [review]
LGTM

**Pull request merged**
