### PR TITLE
Docs: Add search feature

### LINKED ISSUE #1243: Documentation Search Feature
## Feature Request

Add search capabilities to the TCE documentation site.

### PR DESCRIPTION
**Pull request by garrying**
## What this PR does / why we need it
This adds documentation search to `/docs` using DocSearch v3 from Algolia. The index configuration can be found at [algolia/docsearch-configs](https://github.com/algolia/docsearch-configs/blob/master/configs/tanzucommunityedition.json)

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes
Fixes: #1243

## Describe testing done for PR
- `hugo sever`
- Navigate to `/docs/`
- Note: results will resolve to `tanzucommunityedition.io` and not `localhost`

## Special notes for your reviewer
This is migrates DocSearch from v2 to v3.alpha. The v3 interaction is different as it uses a button/overlay to invoke a search interface. We could stick to the v2 input if this doesn't present well.

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
One additional thing we should do in this PR (which I'm happy to help with too) is upgrade the dependency we declare in the `package.json` and `package-lock.json` files under the `docs/site` directory.

This is documented here: https://github.com/vmware-tanzu/community-edition/tree/main/docs/site#npm-dependencies

and is used to enable dependabot to track security vulnerabilities. Let me know if you need help with this!

**Comment by garrying** [comment]
Thanks for the note! Updated `package.json` and `package-lock.json` with the most recent docsearch v3 alpha build. I think having an explicit version/build will make dependency tracking a little easier.

**Comment by dvonthenen** [comment]
will defer to @jpmcb for validation

**Comment by kcoriordan** [comment]
@jpmcb can you validate, thanks

**Review by jpmcb — APPROVED** [review]
Looks great! Thanks for this @garrying !!!!! 🚀

**Pull request merged**
