### PR TITLE
Fixing supported kubernetes versions per v0.11.0

### PR DESCRIPTION
**Pull request by Analect**
These are the supported versions as per OVAs available in customerconnect.vmware.com

## What this PR does / why we need it
Updates kubernetes version support in tanzucommunityedition docs based on OVAs available in customerconnect.vmware.com

## Which issue(s) this PR fixes
NA

Fixes: #

## Describe testing done for PR
None

## Special notes for your reviewer
Based on feedback in TCE slack channel [here](https://kubernetes.slack.com/archives/C02GY94A8KT/p1649066668804209) that this information was correct.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Thanks @Analect - are you able to sign the CLA?

**Comment by dvonthenen** [comment]
yea... I'm going to see about removing our dependency on customer connect and what that would entail

**Review by stmcginnis — APPROVED** [review]
Thanks!

**Comment by stmcginnis** [comment]
@dvonthenen did you get a chance to look at alternatives?

**Pull request closed without merging**
