### PR TITLE
Changed issue templated to yml based templateds and removed MD templates

### LINKED ISSUE #4417: Changing issue templates from Markdown Based to yml based
Changing the issue templates from MD-based to Github Form-Based templates will help in getting some required fields and also set some values as form values. This will also help in structuring the issues and characterize some details like OS information

### PR DESCRIPTION
**Pull request by mohitsharma-in**
## What this PR does / why we need it
Changing issue templates from Markdown Based to yml based

## Which issue(s) this PR fixes

Fixes:  https://github.com/vmware-tanzu/community-edition/issues/4417

## Describe testing done for PR
This can not be tested against fork repo

### CODE REVIEW

**Comment by stmcginnis** [comment]
We had discussed the idea of using issue forms early on and the decision was we did NOT want to force things into a form.

We can see what others think now, but -1 from me on making this change.

**Review by davidvonthenen — APPROVED** [review]

**Review by davidvonthenen — CHANGES_REQUESTED** [review]
Looks like you have YAML errors... I hit the approve button by mistake.

```
/community-edition/.github/ISSUE_TEMPLATE/bug-report.yml
  86:53     error    no new line character at the end of file  (new-line-at-end-of-file)

/community-edition/.github/ISSUE_TEMPLATE/feedback-report.yml
  69:21     error    no new line character at the end of file  (new-line-at-end-of-file)

/community-edition/.github/ISSUE_TEMPLATE/feature-request.yml
  58:21     error    no new line character at the end of file  (new-line-at-end-of-file)
```

**Comment by dvonthenen** [comment]
After thinking about this and understanding what this would look like, the freeform MD is sufficient and there isn't a need to put a lot of enforcible structure around this. -1 for me as well

**Review by jpmcb — COMMENTED** [review]
This is a -1 from me as well.

We should keep the barrier to entry as low as possible for users creating issues, bug reports, and feature requests. While the free-form MD templates provide enough suggestions to be useful, I don't want users to have "required" fields they have to enter just to get some feedback across.

I'd rather have a issue opened that is poorly formatted vs. no issue at all.

**Comment by stmcginnis** [comment]
Thank you for proposing this Mohit, but I think we have consensus that this is not something we want to do. I'm going to close this PR and Issue.

**Pull request closed without merging**
