### PR TITLE
`unmanaged-cluster` uses `v0.10.1` TCE package repo named `tce-core`

### LINKED ISSUE #3180: TCE-repo Package Repository named as "TKG-Core" and still uses v0.9.1 version
## Bug Report
When I create a `unmanaged-cluster` with TCE v0.10, and I query the Package Repositories available in the cluster. I get the below output. 

```
tanzu package repository list -A
| Retrieving repositories...
  NAME                 REPOSITORY                                           TAG                     STATUS               DETAILS  NAMESPACE
  tkg-core-repository  projects.registry.vmware.com/tce/main                0.9.1                   Reconcile succeeded           tanzu-package-repo-global
  tkg-core-repository  projects.registry.vmware.com/tkg/packages/core/repo  v1.21.2_vmware.1-tkg.1  Reconcile succeeded           tkg-system
```

## Expected Behavior

- I expected the name of the TCE Package Repository to be tce-repo and not tkg-core-repository.
- I expected the v0.10 or v0.9.2 repository to be used. 

## Steps to Reproduce the Bug

- Install the Tanzu CLI v0.10
- Create a TCE unmanaged cluster
- Run tanzu package repository list -A

## Environment Details

* Build version (`tanzu version`): v0.10.1 
* Deployment (Managed/Standalone cluster): Unmanaged cluster 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker
* Operating System (client): Mac

### PR DESCRIPTION
**Pull request by jpmcb**
## What this PR does / why we need it
- Bumps the package repo used by TCE to `v0.10.1`
- Names "core" package repo `tce-core` instead of `tkg-core-repository`

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
unmanaged-cluster uses v0.10.1 TCE package repo named tce-core
```

## Which issue(s) this PR fixes
Fixes: #3180

## Describe testing done for PR
Built and deployed a `unmanaged-cluster`

Package repo:

```
❯ tanzu package repository list -A

  NAME                  REPOSITORY                                           TAG                     STATUS               DETAILS  NAMESPACE
  community-repository  projects.registry.vmware.com/tce/main                0.10.1                  Reconciling                   tanzu-package-repo-global
  tkg-core-repository   projects.registry.vmware.com/tkg/packages/core/repo  v1.21.2_vmware.1-tkg.1  Reconcile succeeded           tkg-system

```

Available packages (including kpack)

```
❯ tanzu package available list

  NAME                                           DISPLAY-NAME        SHORT-DESCRIPTION                                                                                                             LATEST-VERSION
  cert-manager.community.tanzu.vmware.com        cert-manager        Certificate management                                                                                                        1.6.1
  contour.community.tanzu.vmware.com             contour             An ingress controller                                                                                                         1.19.1
  external-dns.community.tanzu.vmware.com        external-dns        This package provides DNS synchronization functionality.                                                                      0.10.0
  fluent-bit.community.tanzu.vmware.com          fluent-bit          Fluent Bit is a fast Log Processor and Forwarder                                                                              1.7.5
  gatekeeper.community.tanzu.vmware.com          gatekeeper          policy management                                                                                                             3.7.0
  grafana.community.tanzu.vmware.com             grafana             Visualization and analytics software                                                                                          7.5.7
  harbor.community.tanzu.vmware.com              harbor              OCI Registry                                                                                                                  2.3.3
  knative-serving.community.tanzu.vmware.com     knative-serving     Knative Serving builds on Kubernetes to support deploying and serving of applications and functions as serverless containers  1.0.0
  kpack.community.tanzu.vmware.com               kpack               kpack builds application source code into OCI compliant images using Cloud Native Buildpacks                                  0.5.0
  local-path-storage.community.tanzu.vmware.com  local-path-storage  This package provides local path node storage and primarily supports RWO AccessMode.                                          0.0.20
  multus-cni.community.tanzu.vmware.com          multus-cni          This package provides the ability for enabling attaching multiple network interfaces to pods in Kubernetes                    3.7.1
  prometheus.community.tanzu.vmware.com          prometheus          A time series database for your metrics                                                                                       2.27.0
  velero.community.tanzu.vmware.com              velero              Disaster recovery capabilities                                                                                                1.7.1

```

### CODE REVIEW

**Review by joshrosso — CHANGES_REQUESTED** [review]
Based on your output, looks like both got renamed. Is there a chance we're incorrectly re-using `tkgCoreRepoName`?

image

**Comment by stmcginnis** [comment]
Verified newer TCE repo used:

```
📦 Selected additional package repositories
   projects.registry.vmware.com/tce/main:0.10.1
```

But agree something doesn't look right with repo names.

**Comment by jpmcb** [comment]
@joshrosso - yes we must be incorrectly using it since this looks to be how `v0.10.0` went out:

```
tanzu package repository list -A
| Retrieving repositories...
  NAME                 REPOSITORY                                           TAG                     STATUS               DETAILS  NAMESPACE
  tkg-core-repository  projects.registry.vmware.com/tce/main                0.9.1                   Reconcile succeeded           tanzu-package-repo-global
  tkg-core-repository  projects.registry.vmware.com/tkg/packages/core/repo  v1.21.2_vmware.1-tkg.1  Reconcile succeeded           tkg-system
```

**Comment by joshrosso** [comment]
> @joshrosso - yes we must be incorrectly using it since this looks to be how `v0.10.0` went out:
> 
> ```
> tanzu package repository list -A
> | Retrieving repositories...
>   NAME                 REPOSITORY                                           TAG                     STATUS               DETAILS  NAMESPACE
>   tkg-core-repository  projects.registry.vmware.com/tce/main                0.9.1                   Reconcile succeeded           tanzu-package-repo-global
>   tkg-core-repository  projects.registry.vmware.com/tkg/packages/core/repo  v1.21.2_vmware.1-tkg.1  Reconcile succeeded           tkg-system
> ```

As part of this change, let's be sure to discern the 2.

**Comment by stmcginnis** [comment]
Looks like here: https://github.com/vmware-tanzu/community-edition/blob/main/cli/cmd/plugin/unmanaged-cluster/tanzu/tanzu.go#L221

Should be using `tceRepoName`. Though there is a problem that that code is looping through and adding potentially multiple repos all with the same name.

**Comment by jpmcb** [comment]
Pushed and updated my PR description. Should now be:

```
❯ tanzu package repository list -A

  NAME                  REPOSITORY                                           TAG                     STATUS               DETAILS  NAMESPACE
  community-repository  projects.registry.vmware.com/tce/main                0.10.1                  Reconciling                   tanzu-package-repo-global
  tkg-core-repository   projects.registry.vmware.com/tkg/packages/core/repo  v1.21.2_vmware.1-tkg.1  Reconcile succeeded           tkg-system

```

**Comment by joshrosso** [comment]
lgtm

```
$ k get packagerepository -A
NAMESPACE                   NAME                   AGE   DESCRIPTION
tanzu-package-repo-global   community-repository   15m   Reconcile succeeded
tkg-system                  tkg-core-repository    15m   Reconcile succeeded
```

**Comment by joshrosso** [comment]
> Looks like here: https://github.com/vmware-tanzu/community-edition/blob/main/cli/cmd/plugin/unmanaged-cluster/tanzu/tanzu.go#L221
> 
> Should be using `tceRepoName`. Though there is a problem that that code is looping through and adding potentially multiple repos all with the same name.

Would be good to address this at some point, but for now, assuming we can do it out-of-band from this work.

**Review by joshrosso — APPROVED** [review]

**Pull request merged**
