### PR TITLE
Add/Update troubleshooting/logs docs 

### LINKED ISSUE #3253: Improve scaling docs to include troubleshooting steps
## Description

I am having an issue with scaling and would like to know where the log files are located. It would be helpful if there was a small troubleshooting section on this page (and possibly every page) to detail how to see what is going on for both learning and troubleshooting purposes.

## Location

https://tanzucommunityedition.io/docs/latest/scale-cluster/

## Additional Context

`tanzu cluster get <cluster name>` is handy for an overview, but where do I go from here?

```
$ tanzu cluster get sand1-tanzu-workload01
  NAME                    NAMESPACE  STATUS    CONTROLPLANE  WORKERS  KUBERNETES        ROLES   
  sand1-tanzu-workload01  default    updating  1/1           1/2      v1.21.2+vmware.1  <none>  
ℹ  

Details:

NAME                                                                       READY  SEVERITY  REASON         SINCE  MESSAGE         
/sand1-tanzu-workload01                                                    True                            2d3h                   
├─ClusterInfrastructure - VSphereCluster/sand1-tanzu-workload01            True                            2d3h                   
├─ControlPlane - KubeadmControlPlane/sand1-tanzu-workload01-control-plane  True                            2d3h                   
│ └─Machine/sand1-tanzu-workload01-control-plane-h7q9k                     True                            2d3h                   
└─Workers                                                                                                                         
  └─MachineDeployment/sand1-tanzu-workload01-md-0                                                                                 
    ├─Machine/sand1-tanzu-workload01-md-0-6f4787dd49-6874k                 True                            16h                    
    └─Machine/sand1-tanzu-workload01-md-0-6f4787dd49-cm86j                 False  Warning   CloningFailed  6m37s  1 of 2 completed
    ```

### PR DESCRIPTION
**Pull request by kcoriordan**
## What this PR does / why we need it

This PR replaces: https://github.com/vmware-tanzu/community-edition/pull/4012, reason is that after file/folder restructure to fix edge, it's easier/cleaner for me to just open a new PR. @johnmcbride, can you approve again.
 - [Troubleshoot Clusters with Tanzu Diagnostics](https://tanzucommunityedition.io/docs/v0.11/tanzu-diagnostics/) & [Troubleshoot Cluster Bootstrapping](https://tanzucommunityedition.io/docs/v0.11/tsg-bootstrap/) have largely the same content. This PR combines the common content into [Troubleshoot Clusters with Tanzu Diagnostics](https://tanzucommunityedition.io/docs/v0.11/tanzu-diagnostics/) and deletes [Troubleshoot Cluster Bootstrapping](https://tanzucommunityedition.io/docs/v0.11/tsg-bootstrap/)  - this doesn't introduce new content - it's just restructure

- Creates a new topic with some of the content from [Troubleshoot Cluster Bootstrapping](https://tanzucommunityedition.io/docs/v0.11/tsg-bootstrap/) - Troubleshoot Cluster Deployment Manually - this doesn't introduce new content - it's just restructure

- Adds a new topic to address #3253 

- Fixes the right nav headings in [Cluster Debugging Tips](https://tanzucommunityedition.io/docs/v0.11/tanzu-debugging-tips/) so that there is one nav item per tip. 

- Expands bootstrap glossary term with some content that was in [Troubleshoot Cluster Bootstrapping](https://tanzucommunityedition.io/docs/v0.11/tsg-bootstrap/) 

## Which issue(s) this PR fixes

Fixes: #3253

## Describe testing done for PR
Preview here:https://deploy-preview-4379--quirky-franklin-8969be.netlify.app/docs/edge/tanzu-debugging-tips/

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]
Looks great!

**Review by stmcginnis — COMMENTED** [review]
It looks like there is a reference to the deleted `tsg-bootstrap` file in `docs/site/content/docs/edge/faq-cluster-bootstrapping.md`?

**Review by stmcginnis — CHANGES_REQUESTED** [review]
Verified in the preview it has a broken link. Otherwise looks great.

**Comment by kcoriordan** [comment]
@stmcginnis fixed that link  now

**Review by stmcginnis — APPROVED** [review]

**Pull request merged**
