### PR TITLE
add faq cluster bootstrapping

### PR DESCRIPTION
**Pull request by AlvinRamoutar**
## What this PR does / why we need it
Adding cluster bootstrapping FAQ along with workaround for a common Windows bootstrapping error.

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
- Creating new FAQ cluster bootstrapping subpage
- Adding new FAQ cluster bootstrapping entry for x509: certificate signed by unknown authority when downloading TKG compatibility file error on Windows
```

## Which issue(s) this PR addresses
Addresses: #1398 , #2139 

## Describe testing done for PR
Tested FAQ successfully on a Windows 10 x64 and Windows Server 2019 x64 host.

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
Hi @AlvinRamoutar! Thanks for opening your first PR and diving head first into this issue! Looks like there are some markdown lint problems. You can run the markdown lint script locally from the root of the repository via while iterating
```
make mdlint
```

---

I'll leave it up to @kcoriordan regarding the formatting and new TOC section

**Comment by jpmcb** [comment]
> Fixes: #1398

I don't believe we want that issue to be resolved by this PR. #1398 tracks the original problem when bootstrapping clusters (and captures the now documented workaround from this PR), but we should keep it open so that we can track fixing the root issue

**Comment by AlvinRamoutar** [comment]
> 
> 
> > Fixes: #1398
> 
> I don't believe we want that issue to be resolved by this PR. #1398 tracks the original problem when bootstrapping clusters (and captures the now documented workaround from this PR), but we should keep it open so that we can track fixing the root issue

Agreed. thanks for highlighting this.
I've updated PR OP to 'addresses' rather than fixes.

**Review by jpmcb — COMMENTED** [review]
LGTM! I'll leave it to @kcoriordan to comment on the new TOC and top level page

**Review by kcoriordan — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
