### PR TITLE
Release Workflow Change, Release Branch Creation Workflow

### PR DESCRIPTION
**Pull request by davidvonthenen**
## What this PR does / why we need it

This PR consolidates the GA, Non-GA, and "Fake" (aka Test) release workflows into a single workflow. This is done largely by just defaulting with "`pre-release=true` and also consolidating the GCP upload buckets to a single workflow. The only consequence of this change is that when we are ready to post a "GA" release, a human just needs to uncheck the `pre-release` box before publishing. This is the cause of a good majority of the deletion in this PR (example deletion of "fake" releases in the cut-release/create-release script).

In the `v0.11.0` release, the `release-0.11`  branch created was actually done by hand which (thankfully) we didnt have any problems (since I planned and mapped this out like crazy). I took that "receipe" and turn it into a github action so that we never have to do this by hand again.

To kick off a release (most likely an RC type release) and create it's release branch and also fix up main to set it up for the next version, you can invoke this by simply running the following command:
```
gh workflow run --repo https://github.com/vmware-tanzu/community-edition/ \
  --ref main \
  release-tag-and-branch.yaml \
  --raw-field release_version=v0.3.0-rc.2
```
That command basically means that main branch contains the work for v0.3.0 (which we have cut an rc.1). Invoking the above will create a `release-0.3` branch, tag that branch with `v0.3.0-rc.2` thus subsequently creating a release. Then on main, the version will get bumped to `v0.4.0` and reference `v0.3.0` as the previous release. All while setting up the dev tags on both branches, `v0.3.0-dev.3` and `v0.4.0-dev.1` respectively.

The testing work can be seen here where I simulated a bunch of RC, GA, and release branch creation:
https://github.com/dvonthenen/ghactiontest/actions

We removed using the `release-notes` utility as it just bloated the release notes. Removed all references to the ensure-deps for the util and removed from all workflows.

Other changes:
- "Fake" releases have been renamed to "Test".
- This PR has a TON of clean up also.

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Release Workflow Change, Release Branch Creation Workflow
```

## Which issue(s) this PR fixes

NA

## Describe testing done for PR

Verified all the branching happened as expected. You can see some of the tests done on this repo which mirrors these workflow changes:
https://github.com/dvonthenen/ghactiontest/actions

`make release` with an install of TCE
```
[vonthd@rocky8 community-edition]$ ./release/tce-linux-amd64-v0.12.0-dev.1/install.sh 
+ set +x
====================================
 Installing Tanzu Community Edition
====================================

Installing tanzu cli to /usr/local/bin/tanzu
[sudo] password for vonthd: 

Installing plugin 'builder:v0.11.2'
✔  successfully installed 'builder' plugin
Installing plugin 'codegen:v0.11.2'
✔  successfully installed 'codegen' plugin
Installing plugin 'cluster:v0.11.2'
✔  successfully installed 'cluster' plugin
Installing plugin 'kubernetes-release:v0.11.2'
✔  successfully installed 'kubernetes-release' plugin
Installing plugin 'login:v0.11.2'
✔  successfully installed 'login' plugin
Installing plugin 'management-cluster:v0.11.2'
✔  successfully installed 'management-cluster' plugin
Installing plugin 'package:v0.11.2'
✔  successfully installed 'package' plugin
Installing plugin 'pinniped-auth:v0.11.2'
✔  successfully installed 'pinniped-auth' plugin
Installing plugin 'secret:v0.11.2'
✔  successfully installed 'secret' plugin
Installing plugin 'conformance:v0.12.0-dev.1'
✔  successfully installed 'conformance' plugin
Installing plugin 'diagnostics:v0.12.0-dev.1'
✔  successfully installed 'diagnostics' plugin
Installing plugin 'unmanaged-cluster:v0.12.0-dev.1'
✔  successfully installed 'unmanaged-cluster' plugin

Installation complete!
```

## Special notes for your reviewer

NA

### CODE REVIEW

**Review by stmcginnis — DISMISSED** [review]
Changes look fine to me.

**Comment by dvonthenen** [comment]
Fixed up the description a little since I was referencing my test repo.

**Review by stmcginnis — APPROVED** [review]
Looks good after the update.

**Comment by dvonthenen** [comment]
Merged on flakey delete cluster

**Pull request merged**
