### PR TITLE
Sync next branch with latest changes to main

### PR DESCRIPTION
**Pull request by stmcginnis**
## What this PR does / why we need it

This pulls in the changes to `main` since `next` was branched.

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
Let's do it! 👀

**Comment by stmcginnis** [comment]
Oh shoot. I was trying to just rebase things, but I forgot we only allow "Squash and merge" for PRs. So it's going to squash everything into one giant commit.

I could just force push all the commits to `next` so it basically rebases the branch onto main.

Or we could just do the merge and just have a slightly wonky commit history. I _think_ that all works out in the end when we merge into `main`, but not as clean as I had hoped.

**Comment by jpmcb** [comment]
> we only allow "Squash and merge" for PRs

Last time we did this with the `unmanaged-cluster` branch, we turned that setting off and Josh did the merge, preserving the history. Might be good for this as well

**Comment by nrb** [comment]
> I could just force push all the commits to next so it basically rebases the branch onto main.

👍

**Pull request closed without merging**
