### PR TITLE
E2E Automation Framework implementation for build/fetch TCE, deploy and test  .

### PR DESCRIPTION
**Pull request by ShwethaKumbla**
## What this PR does / why we need it
This PR introduces the implementation for automation framework for build, deploy and test TCE.
          
As part of this PR the package test folder restructuring has been taken care.

This framework provides flexible way to build, deploy and test TCE. 

This PR includes changes for single command to build, deploy and test TCE releases. 
```
ginkgo -v -- --kubeconfig=$KUBECONFIG --packages="external-dns" --version="0.8.0" --provider-name="docker" --cluster-type="standalone" --guest-cluster-name="tce-mycluster" --create-cluster --tce-version="v0.7.0"
```

Using this automation framework we can perform following activities:-
1. Fetch a particular release from github page, install, create standalone cluster and run package testing , tear down cluster.
2. Build or make release from source code, install, create standalone cluster and run package testing, tear down the cluster.
3. This framework allows you to run only package testing, when standalone cluster is already available. 
4. Individual package testing can be triggered using this framework.
5. This can be wired in CI or github action for PR checking, release build and nightly build process.

## Details for the Release Notes (PLEASE PROVIDE)
```
Implemented E2E Automation Framework for TCE build, deploy and test on CAPD
```

## Scope 
Currently this Automation framework supports following:
1. Complete e2e test(Build, Deploy and Test) of TCE is handled for CAPD standalone and managed clusters.
2. Supports Package testing for CAPA deployments.

## Which issue(s) this PR fixes
Fixes: Get rid of manual testing.

## Special notes for your reviewer
[Readme](https://github.com/vmware-tanzu/tce/pull/1123/files#diff-00dcd663f721d552550d7df5f0a3e41539b9d78ff0ad336a79250f7f619e62df) has the details on how to use this framework.

### CODE REVIEW

**Review by navidshaikh — CHANGES_REQUESTED** [review]
We should improve
 - error handling and reporting
 - how flags are assigned and re-used
 - how dependencies (please rename to testdata or fixtures) are organised
 - scoping this changeset only for CAPD

**Review by navidshaikh — CHANGES_REQUESTED** [review]
I think we should descope this PR: remove any cluster creation/deletion utilities and only focus on executing the package tests (or other tests) assuming the cluster is brought up and ready. IMO, the existing (shell scripts) for cluster lifecycle is well tested and we can rely on them to bring the cluster up.

**Review by stmcginnis — DISMISSED** [review]
Please squash your commits and provide a detailed commit message for the changes. Thanks!

**Review by davidvonthenen — COMMENTED** [review]
Code-wise this seems pretty good to me, but I don't have context for decisions or what the planned/desired end state it. Just had a couple of comments relating to process.

**Review by davidvonthenen — DISMISSED** [review]
This looks good to me code-wise, but I also don't have full context on what the stated/future objectives are.

**Review by christianang — CHANGES_REQUESTED** [review]

**Review by christianang — APPROVED** [review]

**Review by navidshaikh — APPROVED** [review]
lgtm as first iteration for the framework, a few things we should consider for follow up:

- invoking the `e2e-test` target for each package e2e tests
- avoiding use of global config
- better error handling and reporting

**Pull request merged**
