### PR TITLE
add ytt schema for external-dns package

### PR DESCRIPTION
**Pull request by adobley**
## What this PR does / why we need it

this provides defaults and validation for the package

## Which issue(s) this PR fixes

Fixes: #

## Describe testing done for PR

Tested rendering with different inputs to ensure the schema behaved as expected

### CODE REVIEW

**Review by tylerschultz — COMMENTED** [review]
LGTM

**Review by tylerschultz — DISMISSED** [review]

**Comment by tylerschultz** [comment]
The package has changed, which would need a package bump. This PR or another?

**Comment by christianang** [comment]
> The package has changed, which would need a package bump. This PR or another?

After some offline team discussion, the consensus is to merge this PR without releasing a new package artifacts and bumping the package in another PR when we better understand how we want to version new releases of the 0.11.0 package.

**Review by christianang — APPROVED** [review]
LGTM

**Pull request merged**
