### PR TITLE
Merge "next" post-v0.10.0 development to main

### PR DESCRIPTION
**Pull request by stmcginnis**
While waiting for the v0.10.0 release to be ready to merge, we needed to hold off
on merging major changes to `main`. We decided to continue development on the
`next` branch while waiting.

This merges the work that was committed to `next` back to `main` to get the
mainline development back on track.

### CODE REVIEW

**Comment by jpmcb** [comment]
For this PR let's: 🏷️ 
- [ ] Verify `make` targets still work
- [ ] Resovled `.github/workflows/check-pr-docker-standalone.yaml` conflict. That file should be deleted by this PR since standalone is being removed

**Comment by jpmcb** [comment]
## Validating the `make` targets

Methodology - ran `make clean` and `./hack/release/uninstall.sh` between each make target

---

🟢  `make build-tce-cli-plugins`

<details>
<summary>Details</summary>
  
```
❯ tree artifacts
artifacts
├── darwin
│   ├── amd64
│   │   └── cli
│   │       ├── conformance
│   │       │   ├── plugin.yaml
│   │       │   └── v0.10.0-dev.5
│   │       │       ├── tanzu-conformance-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-conformance-test-darwin_amd64
│   │       ├── diagnostics
│   │       │   ├── plugin.yaml
│   │       │   └── v0.10.0-dev.5
│   │       │       ├── tanzu-diagnostics-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-diagnostics-test-darwin_amd64
│   │       ├── manifest.yaml
│   │       └── unmanaged-cluster
│   │           ├── plugin.yaml
│   │           └── v0.10.0-dev.5
│   │               ├── tanzu-unmanaged-cluster-darwin_amd64
│   │               └── test
│   │                   └── tanzu-unmanaged-cluster-test-darwin_amd64
│   └── arm64
│       └── cli
│           ├── conformance
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-conformance-darwin_arm64
│           │       └── test
│           │           └── tanzu-conformance-test-darwin_arm64
│           ├── diagnostics
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-diagnostics-darwin_arm64
│           │       └── test
│           │           └── tanzu-diagnostics-test-darwin_arm64
│           ├── manifest.yaml
│           └── unmanaged-cluster
│               ├── plugin.yaml
│               └── v0.10.0-dev.5
│                   ├── tanzu-unmanaged-cluster-darwin_arm64
│                   └── test
│                       └── tanzu-unmanaged-cluster-test-darwin_arm64
├── linux
│   └── amd64
│       └── cli
│           ├── conformance
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-conformance-linux_amd64
│           │       └── test
│           │           └── tanzu-conformance-test-linux_amd64
│           ├── diagnostics
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-diagnostics-linux_amd64
│           │       └── test
│           │           └── tanzu-diagnostics-test-linux_amd64
│           ├── manifest.yaml
│           └── unmanaged-cluster
│               ├── plugin.yaml
│               └── v0.10.0-dev.5
│                   ├── tanzu-unmanaged-cluster-linux_amd64
│                   └── test
│                       └── tanzu-unmanaged-cluster-test-linux_amd64
└── windows
    └── amd64
        └── cli
            ├── conformance
            │   ├── plugin.yaml
            │   └── v0.10.0-dev.5
            │       ├── tanzu-conformance-windows_amd64.exe
            │       └── test
            │           └── tanzu-conformance-test-windows_amd64.exe
            ├── diagnostics
            │   ├── plugin.yaml
            │   └── v0.10.0-dev.5
            │       ├── tanzu-diagnostics-windows_amd64.exe
            │       └── test
            │           └── tanzu-diagnostics-test-windows_amd64.exe
            ├── manifest.yaml
            └── unmanaged-cluster
                ├── plugin.yaml
                └── v0.10.0-dev.5
                    ├── tanzu-unmanaged-cluster-windows_amd64.exe
                    └── test
                        └── tanzu-unmanaged-cluster-test-windows_amd64.exe

47 directories, 40 files

```
</details>

---

🔴 `make install-tce-cli-plugins`

<details>
<summary>Details</summary>

failed at the following step:
```
TANZU_CLI_NO_INIT=true go run -ldflags "-s -w -X "github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/tkgconfigpaths.TKGDefaultImageRepo="projects-stg.registry.vmware.com/tkg"" -X "github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/tkgconfigpaths.TKGDefaultCompatibilityImagePath="framework-zshippable/tkg-compatibility"" -X "github.com/vmware-tanzu/tanzu-framework/pkg/v1/buildinfo.Date=$(date -u +"%Y-%m-%d")" -X "github.com/vmware-tanzu/tanzu-framework/pkg/v1/buildinfo.SHA=$(git rev-parse --short HEAD)" -X "github.com/vmware-tanzu/tanzu-framework/pkg/v1/buildinfo.Version=v0.10.0-dev.5" -X 'github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/buildinfo.IsOfficialBuild=""' -X 'github.com/vmware-tanzu/community-edition/cli/cmd/plugin.Date=$(date -u +"%Y-%m-%d")' -X 'github.com/vmware-tanzu/community-edition/cli/cmd/plugin.SHA=$(git rev-parse --short HEAD)' -X 'github.com/vmware-tanzu/community-edition/cli/cmd/plugin.Version=v0.10.0-dev.5' -X "github.com/vmware-tanzu/sonobuoy/pkg/buildinfo.Version=v0.53.2"" github.com/vmware-tanzu/tanzu-framework/cmd/cli/tanzu \
        plugin install all --local ../../build/linux-amd64-default
Error: could not find manifest.yaml file: open ../../build/linux-amd64-default/manifest.yaml: no such file or directory

✖  could not find manifest.yaml file: open ../../build/linux-amd64-default/manifest.yaml: no such file or directory
exit status 1
make[1]: *** [Makefile:112: install-plugins] Error 1
make[1]: Leaving directory '/home/jmcb/workspace/github.com/vmware-tanzu/tce/hack/builder'
make: *** [Makefile:387: install-plugins] Error 2

```

The build tree looks like:
```
❯ tree build
build
├── darwin-amd64-default
│   ├── discovery
│   │   └── default
│   │       ├── conformance.yaml
│   │       ├── diagnostics.yaml
│   │       └── unmanaged-cluster.yaml
│   └── distribution
│       └── darwin
│           └── amd64
│               └── cli
│                   ├── conformance
│                   │   └── v0.10.0-dev.5
│                   │       └── tanzu-conformance-darwin_amd64
│                   ├── diagnostics
│                   │   └── v0.10.0-dev.5
│                   │       └── tanzu-diagnostics-darwin_amd64
│                   └── unmanaged-cluster
│                       └── v0.10.0-dev.5
│                           └── tanzu-unmanaged-cluster-darwin_amd64
├── darwin-arm64-default
│   ├── discovery
│   │   └── default
│   │       ├── conformance.yaml
│   │       ├── diagnostics.yaml
│   │       └── unmanaged-cluster.yaml
│   └── distribution
│       └── darwin
│           └── arm64
│               └── cli
│                   ├── conformance
│                   │   └── v0.10.0-dev.5
│                   │       └── tanzu-conformance-darwin_arm64
│                   ├── diagnostics
│                   │   └── v0.10.0-dev.5
│                   │       └── tanzu-diagnostics-darwin_arm64
│                   └── unmanaged-cluster
│                       └── v0.10.0-dev.5
│                           └── tanzu-unmanaged-cluster-darwin_arm64
├── linux-amd64-default
│   ├── discovery
│   │   └── default
│   │       ├── conformance.yaml
│   │       ├── diagnostics.yaml
│   │       └── unmanaged-cluster.yaml
│   └── distribution
│       └── linux
│           └── amd64
│               └── cli
│                   ├── conformance
│                   │   └── v0.10.0-dev.5
│                   │       └── tanzu-conformance-linux_amd64
│                   ├── diagnostics
│                   │   └── v0.10.0-dev.5
│                   │       └── tanzu-diagnostics-linux_amd64
│                   └── unmanaged-cluster
│                       └── v0.10.0-dev.5
│                           └── tanzu-unmanaged-cluster-linux_amd64
└── windows-amd64-default
    ├── discovery
    │   └── default
    │       ├── conformance.yaml
    │       ├── diagnostics.yaml
    │       └── unmanaged-cluster.yaml
    └── distribution
        └── windows
            └── amd64
                └── cli
                    ├── conformance
                    │   └── v0.10.0-dev.5
                    │       └── tanzu-conformance-windows_amd64.exe
                    ├── diagnostics
                    │   └── v0.10.0-dev.5
                    │       └── tanzu-diagnostics-windows_amd64.exe
                    └── unmanaged-cluster
                        └── v0.10.0-dev.5
                            └── tanzu-unmanaged-cluster-windows_amd64.exe

```
We might need to update this job to look for the new directory structure
</details>

---

🟢 `make build-all-tanzu-cli-plugins`

<details>
  <summary>Details</summary>
  
```
❯ tree artifacts
artifacts
├── darwin
│   ├── amd64
│   │   └── cli
│   │       ├── conformance
│   │       │   ├── plugin.yaml
│   │       │   └── v0.10.0-dev.5
│   │       │       ├── tanzu-conformance-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-conformance-test-darwin_amd64
│   │       ├── diagnostics
│   │       │   ├── plugin.yaml
│   │       │   └── v0.10.0-dev.5
│   │       │       ├── tanzu-diagnostics-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-diagnostics-test-darwin_amd64
│   │       ├── manifest.yaml
│   │       └── unmanaged-cluster
│   │           ├── plugin.yaml
│   │           └── v0.10.0-dev.5
│   │               ├── tanzu-unmanaged-cluster-darwin_amd64
│   │               └── test
│   │                   └── tanzu-unmanaged-cluster-test-darwin_amd64
│   └── arm64
│       └── cli
│           ├── conformance
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-conformance-darwin_arm64
│           │       └── test
│           │           └── tanzu-conformance-test-darwin_arm64
│           ├── diagnostics
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-diagnostics-darwin_arm64
│           │       └── test
│           │           └── tanzu-diagnostics-test-darwin_arm64
│           ├── manifest.yaml
│           └── unmanaged-cluster
│               ├── plugin.yaml
│               └── v0.10.0-dev.5
│                   ├── tanzu-unmanaged-cluster-darwin_arm64
│                   └── test
│                       └── tanzu-unmanaged-cluster-test-darwin_arm64
├── linux
│   └── amd64
│       └── cli
│           ├── conformance
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-conformance-linux_amd64
│           │       └── test
│           │           └── tanzu-conformance-test-linux_amd64
│           ├── diagnostics
│           │   ├── plugin.yaml
│           │   └── v0.10.0-dev.5
│           │       ├── tanzu-diagnostics-linux_amd64
│           │       └── test
│           │           └── tanzu-diagnostics-test-linux_amd64
│           ├── manifest.yaml
│           └── unmanaged-cluster
│               ├── plugin.yaml
│               └── v0.10.0-dev.5
│                   ├── tanzu-unmanaged-cluster-linux_amd64
│                   └── test
│                       └── tanzu-unmanaged-cluster-test-linux_amd64
└── windows
    └── amd64
        └── cli
            ├── conformance
            │   ├── plugin.yaml
            │   └── v0.10.0-dev.5
            │       ├── tanzu-conformance-windows_amd64.exe
            │       └── test
            │           └── tanzu-conformance-test-windows_amd64.exe
            ├── diagnostics
            │   ├── plugin.yaml
            │   └── v0.10.0-dev.5
            │       ├── tanzu-diagnostics-windows_amd64.exe
            │       └── test
            │           └── tanzu-diagnostics-test-windows_amd64.exe
            ├── manifest.yaml
            └── unmanaged-cluster
                ├── plugin.yaml
                └── v0.10.0-dev.5
                    ├── tanzu-unmanaged-cluster-windows_amd64.exe
                    └── test
                        └── tanzu-unmanaged-cluster-test-windows_amd64.exe

47 directories, 40 files
❯ tree /tmp/tce-scratch-space/tanzu-framework/artifacts
/tmp/tce-scratch-space/tanzu-framework/artifacts
├── darwin
│   ├── amd64
│   │   └── cli
│   │       ├── cluster
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-cluster-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-cluster-test-darwin_amd64
│   │       ├── core
│   │       │   ├── latest
│   │       │   │   └── tanzu-core-darwin_amd64
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       └── tanzu-core-darwin_amd64
│   │       ├── feature
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-feature-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-feature-test-darwin_amd64
│   │       ├── kubernetes-release
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-kubernetes-release-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-kubernetes-release-test-darwin_amd64
│   │       ├── login
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-login-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-login-test-darwin_amd64
│   │       ├── management-cluster
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-management-cluster-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-management-cluster-test-darwin_amd64
│   │       ├── manifest.yaml
│   │       ├── package
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-package-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-package-test-darwin_amd64
│   │       ├── pinniped-auth
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-pinniped-auth-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-pinniped-auth-test-darwin_amd64
│   │       └── secret
│   │           ├── plugin.yaml
│   │           └── v0.16.0
│   │               ├── tanzu-secret-darwin_amd64
│   │               └── test
│   │                   └── tanzu-secret-test-darwin_amd64
│   └── arm64
│       └── cli
│           ├── cluster
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-cluster-darwin_arm64
│           │       └── test
│           │           └── tanzu-cluster-test-darwin_arm64
│           ├── core
│           │   ├── latest
│           │   │   └── tanzu-core-darwin_arm64
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       └── tanzu-core-darwin_arm64
│           ├── feature
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-feature-darwin_arm64
│           │       └── test
│           │           └── tanzu-feature-test-darwin_arm64
│           ├── kubernetes-release
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-kubernetes-release-darwin_arm64
│           │       └── test
│           │           └── tanzu-kubernetes-release-test-darwin_arm64
│           ├── login
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-login-darwin_arm64
│           │       └── test
│           │           └── tanzu-login-test-darwin_arm64
│           ├── management-cluster
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-management-cluster-darwin_arm64
│           │       └── test
│           │           └── tanzu-management-cluster-test-darwin_arm64
│           ├── manifest.yaml
│           ├── package
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-package-darwin_arm64
│           │       └── test
│           │           └── tanzu-package-test-darwin_arm64
│           ├── pinniped-auth
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-pinniped-auth-darwin_arm64
│           │       └── test
│           │           └── tanzu-pinniped-auth-test-darwin_arm64
│           └── secret
│               ├── plugin.yaml
│               └── v0.16.0
│                   ├── tanzu-secret-darwin_arm64
│                   └── test
│                       └── tanzu-secret-test-darwin_arm64
├── linux
│   └── amd64
│       └── cli
│           ├── cluster
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-cluster-linux_amd64
│           │       └── test
│           │           └── tanzu-cluster-test-linux_amd64
│           ├── core
│           │   ├── latest
│           │   │   └── tanzu-core-linux_amd64
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       └── tanzu-core-linux_amd64
│           ├── feature
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-feature-linux_amd64
│           │       └── test
│           │           └── tanzu-feature-test-linux_amd64
│           ├── kubernetes-release
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-kubernetes-release-linux_amd64
│           │       └── test
│           │           └── tanzu-kubernetes-release-test-linux_amd64
│           ├── login
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-login-linux_amd64
│           │       └── test
│           │           └── tanzu-login-test-linux_amd64
│           ├── management-cluster
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-management-cluster-linux_amd64
│           │       └── test
│           │           └── tanzu-management-cluster-test-linux_amd64
│           ├── manifest.yaml
│           ├── package
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-package-linux_amd64
│           │       └── test
│           │           └── tanzu-package-test-linux_amd64
│           ├── pinniped-auth
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-pinniped-auth-linux_amd64
│           │       └── test
│           │           └── tanzu-pinniped-auth-test-linux_amd64
│           └── secret
│               ├── plugin.yaml
│               └── v0.16.0
│                   ├── tanzu-secret-linux_amd64
│                   └── test
│                       └── tanzu-secret-test-linux_amd64
└── windows
    └── amd64
        └── cli
            ├── cluster
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-cluster-windows_amd64.exe
            │       └── test
            │           └── tanzu-cluster-test-windows_amd64.exe
            ├── core
            │   ├── latest
            │   │   └── tanzu-core-windows_amd64.exe
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       └── tanzu-core-windows_amd64.exe
            ├── feature
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-feature-windows_amd64.exe
            │       └── test
            │           └── tanzu-feature-test-windows_amd64.exe
            ├── kubernetes-release
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-kubernetes-release-windows_amd64.exe
            │       └── test
            │           └── tanzu-kubernetes-release-test-windows_amd64.exe
            ├── login
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-login-windows_amd64.exe
            │       └── test
            │           └── tanzu-login-test-windows_amd64.exe
            ├── management-cluster
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-management-cluster-windows_amd64.exe
            │       └── test
            │           └── tanzu-management-cluster-test-windows_amd64.exe
            ├── manifest.yaml
            ├── package
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-package-windows_amd64.exe
            │       └── test
            │           └── tanzu-package-test-windows_amd64.exe
            ├── pinniped-auth
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-pinniped-auth-windows_amd64.exe
            │       └── test
            │           └── tanzu-pinniped-auth-test-windows_amd64.exe
            └── secret
                ├── plugin.yaml
                └── v0.16.0
                    ├── tanzu-secret-windows_amd64.exe
                    └── test
                        └── tanzu-secret-test-windows_amd64.exe

119 directories, 112 files
❯ tree /tmp/tce-scratch-space/tanzu-framework/artifacts-admin
/tmp/tce-scratch-space/tanzu-framework/artifacts-admin
├── darwin
│   ├── amd64
│   │   └── cli
│   │       ├── builder
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-builder-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-builder-test-darwin_amd64
│   │       ├── codegen
│   │       │   ├── plugin.yaml
│   │       │   └── v0.16.0
│   │       │       ├── tanzu-codegen-darwin_amd64
│   │       │       └── test
│   │       │           └── tanzu-codegen-test-darwin_amd64
│   │       ├── manifest.yaml
│   │       └── test
│   │           ├── plugin.yaml
│   │           └── v0.16.0
│   │               ├── tanzu-test-darwin_amd64
│   │               └── test
│   │                   └── tanzu-test-test-darwin_amd64
│   └── arm64
│       └── cli
│           ├── builder
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-builder-darwin_arm64
│           │       └── test
│           │           └── tanzu-builder-test-darwin_arm64
│           ├── codegen
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-codegen-darwin_arm64
│           │       └── test
│           │           └── tanzu-codegen-test-darwin_arm64
│           ├── manifest.yaml
│           └── test
│               ├── plugin.yaml
│               └── v0.16.0
│                   ├── tanzu-test-darwin_arm64
│                   └── test
│                       └── tanzu-test-test-darwin_arm64
├── linux
│   └── amd64
│       └── cli
│           ├── builder
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-builder-linux_amd64
│           │       └── test
│           │           └── tanzu-builder-test-linux_amd64
│           ├── codegen
│           │   ├── plugin.yaml
│           │   └── v0.16.0
│           │       ├── tanzu-codegen-linux_amd64
│           │       └── test
│           │           └── tanzu-codegen-test-linux_amd64
│           ├── manifest.yaml
│           └── test
│               ├── plugin.yaml
│               └── v0.16.0
│                   ├── tanzu-test-linux_amd64
│                   └── test
│                       └── tanzu-test-test-linux_amd64
└── windows
    └── amd64
        └── cli
            ├── builder
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-builder-windows_amd64.exe
            │       └── test
            │           └── tanzu-builder-test-windows_amd64.exe
            ├── codegen
            │   ├── plugin.yaml
            │   └── v0.16.0
            │       ├── tanzu-codegen-windows_amd64.exe
            │       └── test
            │           └── tanzu-codegen-test-windows_amd64.exe
            ├── manifest.yaml
            └── test
                ├── plugin.yaml
                └── v0.16.0
                    ├── tanzu-test-windows_amd64.exe
                    └── test
                        └── tanzu-test-test-windows_amd64.exe

47 directories, 40 files
```
</details>

---

🟢  `make install-all-tanzu-cli-plugins`

<details>
<summary>Details</summary>
  
```
❯ tanzu plugin list
unable to list plugin from discovery 'default-local': error while reading local plugin manifest directory: open /home/jmcb/.config/tanzu-plugins/discovery/standalone: no such file or directory
  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY  VERSION        STATUS
  cluster             Kubernetes cluster operations                                      Standalone             v0.16.0        installed
  feature             Operate on features and featuregates                               Standalone             v0.16.0        installed
  kubernetes-release  Kubernetes release operations                                      Standalone             v0.16.0        installed
  management-cluster  Kubernetes management cluster operations                           Standalone             v0.16.0        installed
  package             Tanzu package management                                           Standalone             v0.16.0        installed
  secret              Tanzu secret management                                            Standalone             v0.16.0        installed
  builder             Build Tanzu components                                             Standalone             v0.16.0        installed
  conformance         Run Sonobuoy conformance tests against clusters                    Standalone             v0.10.0-dev.5  installed
  diagnostics         Cluster diagnostics                                                Standalone             v0.10.0-dev.5  installed
  login               Login to the platform                                              Standalone             v0.16.0        installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone             v0.16.0        installed
  unmanaged-cluster   Deploy and manage single-node, static, Tanzu clusters.             Standalone             v0.10.0-dev.5  installed
  codegen             Tanzu code generation tool                                         Standalone             v0.16.0        installed

```
</details>

---

🟢 `make release`

<details>
<summary>Details</summary>

```
❯ ./install.sh
+ ALLOW_INSTALL_AS_ROOT=
+ [[ 1000 -eq 0 ]]
+++ dirname ./install.sh
++ cd .
++ pwd
+ MY_DIR=/home/jmcb/workspace/github.com/vmware-tanzu/tce/release/tce-linux-amd64-v0.10.0-dev.5
++ uname
+ BUILD_OS=Linux
+ case "${BUILD_OS}" in
+ XDG_DATA_HOME=/home/jmcb/.local/share
+ echo /home/jmcb/.local/share
/home/jmcb/.local/share
++ command -v tanzu
+ TANZU_BIN_PATH=
+ [[ -n '' ]]
+ TANZU_BIN_PATH=/usr/local/bin
+ [[ :/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/jmcb/.nvm/versions/node/v17.4.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/jmcb/.cargo/bin:/home/jmcb/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/jmcb/go/bin:/usr/local/go/bin:/home/jmcb/go/bin: == *\:\/\h\o\m\e\/\j\m\c\b\/\b\i\n\:* ]]
+ echo Installing tanzu cli to /usr/local/bin
Installing tanzu cli to /usr/local/bin
+ sudo install /home/jmcb/workspace/github.com/vmware-tanzu/tce/release/tce-linux-amd64-v0.10.0-dev.5/tanzu /usr/local/bin
+ mkdir -p /home/jmcb/.local/share/tce
+ install /home/jmcb/workspace/github.com/vmware-tanzu/tce/release/tce-linux-amd64-v0.10.0-dev.5/uninstall.sh /home/jmcb/.local/share/tce
+ TANZU_PLUGIN_CACHE=/home/jmcb/.cache/tanzu/catalog.yaml
+ [[ -n /home/jmcb/.cache/tanzu/catalog.yaml ]]
+ echo 'Removing old plugin cache from /home/jmcb/.cache/tanzu/catalog.yaml'
Removing old plugin cache from /home/jmcb/.cache/tanzu/catalog.yaml
+ rm -f /home/jmcb/.cache/tanzu/catalog.yaml
++ find /home/jmcb/workspace/github.com/vmware-tanzu/tce/release/tce-linux-amd64-v0.10.0-dev.5 -maxdepth 1 -type d -name '*-default' -exec basename '{}' ';'
+ platformdir=linux-amd64-default
+ tanzu plugin install all --local /home/jmcb/workspace/github.com/vmware-tanzu/tce/release/tce-linux-amd64-v0.10.0-dev.5/linux-amd64-default
Installing plugin 'builder:v0.16.0'
Installing plugin 'codegen:v0.16.0'
Installing plugin 'cluster:v0.16.0'
Installing plugin 'conformance:v0.10.0-dev.5'
Installing plugin 'diagnostics:v0.10.0-dev.5'
Installing plugin 'feature:v0.16.0'
Installing plugin 'kubernetes-release:v0.16.0'
Installing plugin 'login:v0.16.0'
Installing plugin 'management-cluster:v0.16.0'
Installing plugin 'package:v0.16.0'
Installing plugin 'pinniped-auth:v0.16.0'
Installing plugin 'secret:v0.16.0'
Installing plugin 'unmanaged-cluster:v0.10.0-dev.5'
✔  successfully installed 'all' plugin
+ tanzu init
Checking for required plugins...
unable to list plugin from discovery 'default-local': error while reading local plugin manifest directory: open /home/jmcb/.config/tanzu-plugins/discovery/standalone: no such file or directory
All required plugins are already installed and up-to-date
✔  successfully initialized CLI
++ tanzu plugin repo list
++ grep tce
+ TCE_REPO=
+ [[ -z '' ]]
+ tanzu plugin repo add --name tce --gcp-bucket-name tce-tanzu-cli-plugins --gcp-root-path artifacts
++ tanzu plugin repo list
++ grep core-admin
+ TCE_REPO=
+ [[ -z '' ]]
+ tanzu plugin repo add --name core-admin --gcp-bucket-name tce-tanzu-cli-framework-admin --gcp-root-path artifacts-admin
+ echo 'Installation complete!'
Installation complete!
❯ tanzu plugin list
unable to list plugin from discovery 'default-local': error while reading local plugin manifest directory: open /home/jmcb/.config/tanzu-plugins/discovery/standalone: no such file or directory
  NAME                DESCRIPTION                                                        SCOPE       DISCOVERY  VERSION        STATUS
  unmanaged-cluster   Deploy and manage single-node, static, Tanzu clusters.             Standalone             v0.10.0-dev.5  installed
  builder             Build Tanzu components                                             Standalone             v0.16.0        installed
  cluster             Kubernetes cluster operations                                      Standalone             v0.16.0        installed
  conformance         Run Sonobuoy conformance tests against clusters                    Standalone             v0.10.0-dev.5  installed
  login               Login to the platform                                              Standalone             v0.16.0        installed
  management-cluster  Kubernetes management cluster operations                           Standalone             v0.16.0        installed
  package             Tanzu package management                                           Standalone             v0.16.0        installed
  secret              Tanzu secret management                                            Standalone             v0.16.0        installed
  codegen             Tanzu code generation tool                                         Standalone             v0.16.0        installed
  diagnostics         Cluster diagnostics                                                Standalone             v0.10.0-dev.5  installed
  feature             Operate on features and featuregates                               Standalone             v0.16.0        installed
  kubernetes-release  Kubernetes release operations                                      Standalone             v0.16.0        installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)  Standalone             v0.16.0        installed
```
</details>

**Comment by dvonthenen** [comment]
@stmcginnis @jpmcb  If I remember correctly, the failure on `make install-tce-cli-plugins` was by design but we aren't erroring out gracefully. I think things changed enough, where this is no longer in the code path:
https://github.com/vmware-tanzu/community-edition/blob/main/hack/builder/install-tanzu.sh#L18-L21

I think if we want to add back `install-cli` as a prereq, I think that should trigger the friendly failure. We can do that in a subsequent PR though.

**Review by davidvonthenen — DISMISSED** [review]
I'm good as long as all the tests pass 😬

**Review by 12345lcr — DISMISSED** [review]

**Comment by dvonthenen** [comment]
The failures in create management cluster are due to pointing to the wrong BOM. This can be corrected post merge.

**Review by jpmcb — DISMISSED** [review]

**Review by davidvonthenen — APPROVED** [review]

**Pull request merged**
