### PR TITLE
Package update for v0.12.0 #4073

### LINKED ISSUE #4073: Package Updates for v0.12.0
## Feature Request

Need to update the package repo to include the latest packages. Ensure that main.yaml has the following:

app-toolkit 0.y.z (work still in progress, no PR yet)
cartographer 0.3.0
cartographer-catalog 0.3.0 (see #3984)
cert-manager 1.5.5
cert-manager 1.6.3
cert-manager 1.7.2
cert-manager 1.8.0
fluxcd-kustomize-controller 0.21.1
gatekeeper 3.7.1
kpack-dependencies 0.0.9
local-path-storage 0.0.22
whereabouts 0.5.1

### PR DESCRIPTION
**Pull request by seemiller**
## What this PR does / why we need it

Adds new and updated packages to the main package repository.

## Which issue(s) this PR fixes

Fixes: #4073

### CODE REVIEW

**Comment by joshrosso** [comment]
rebased against `main` today to include `cartographer-catalog`.

cartographer-catalog is now available in:

```
projects.registry.vmware.com/tce/main:0.12.0-rc3
```

**Comment by seemiller** [comment]
added flucd-source-controller v0.21.5 ->
```
projects.registry.vmware.com/tce/main@sha256:510f3107fcd7e9f868974e81ec0b7e8684e94e0772f1a1f86b324165535dde61
```

**Comment by seemiller** [comment]
Add kpack-dependencies 0.0.27, tag `v0.12.0-rc7`
```
projects-stg.registry.vmware.com/tce/main@sha256:00317a1fdc43a1582a6ccc3313ec19a7973912e00bd7c832c3907331a773d093
```

**Comment by seemiller** [comment]
added fluxcd-helm-controller 0.17.2 - `v0.12.0-rc8`
```
projects-stg.registry.vmware.com/tce/main@sha256:87c0f01c88e0ebb8e05904d12acb8450383d30cd7d9ce3bcaf7b3a09a25ec60b
```

**Comment by seemiller** [comment]
Pushed repo to distribution Harbor, tagged `v0.12.0-rc8`:

```
projects.registry.vmware.com/tce/main@sha256:87c0f01c88e0ebb8e05904d12acb8450383d30cd7d9ce3bcaf7b3a09a25ec60b
```

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
