### PR TITLE
Add YAML linter github workflow

### PR DESCRIPTION
**Pull request by aman556**
## What this PR does / why we need it

 - Run yamllinter from a docker container cytopia/yamllint
 - Refer hack/.yamllintconfig.yaml config to control the yamllint gates
   - currently only new-line-at-end-of-file rule is enabled to minimize
      the chageset in the PR
    - next iteration could enable a rule at a time and update the yamls
         accordingly
 - Also update all the yaml files in repo to fix the enabled rule
 - Add .github/workflows/check-yaml.yaml github workflow for yamllint

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Add YAML linter github workflow presubmit check. Devs can verify locally using `make yamllint`.
```
## Which issue(s) this PR fixes

Related to https://github.com/vmware-tanzu/tce/issues/1173
## Describe testing done for PR

- Run `make yamllint` and ensure no errors are returned by yamllint and it exits with 0

## Special notes for your reviewer

Only enabled `new-line-at-end-of-file` rule in yamllint config for now to keep the PR changeset size reviewable.
Plan is to open subsequent PRs with fixes and more rules enabled.

### CODE REVIEW

**Review by karuppiah7890 — CHANGES_REQUESTED** [review]

**Review by karuppiah7890 — CHANGES_REQUESTED** [review]

**Review by navidshaikh — CHANGES_REQUESTED** [review]
lets use yamllint configuration with the linter

**Review by nicolehanjing — COMMENTED** [review]
CPI changes are looking good to me

**Review by sabbey37 — APPROVED** [review]
Pinniped changes look good! Thank you for doing this! (:

**Review by jpmcb — CHANGES_REQUESTED** [review]

**Review by davidvonthenen — COMMENTED** [review]
Great idea for yaml checking!

**Review by davidvonthenen — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
Thanks for the quick update on the changes! This looks good to me and will merge 🚀

**Review by carlisia — CHANGES_REQUESTED** [review]
One request to include this linter in the list of linters of the makefile.

**Review by karuppiah7890 — APPROVED** [review]

**Review by navidshaikh — APPROVED** [review]

**Review by LukeWinikates — APPROVED** [review]
Did a quick skim of the grafana/prometheus changes, which all seem to be whitespace changes. That looks fine to me. The rest of the changes are outside of my scope.

**Review by stmcginnis — APPROVED** [review]
Changes look good, and commit message clearly explains what changes are being done. Looks good to me!

**Pull request merged**
