### PR TITLE
Update framework to v0.11.2

### LINKED ISSUE #3230: Updating TCE to 0.10 fails with an error during kubectl apply.
## Bug Report

Upgrading TCE to 0.10 fails with an error during kubectl apply.

## Expected Behavior

The upgrade succeeds.

## Screenshots or additional information and context

The error that it fails with: `Error: unable to upgrade management cluster: failed to update metadata configmaps after kubernetes upgrade: error while upgrading additional component 'addons-management/standard-package-repo': kubectl apply failed, output: error: no objects passed to apply
: exit status 1`

## Environment Details

* Build version (`tanzu version`): v0.10.1
* Deployment (Managed/Standalone cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere): vSphere 
* Operating System (client): macOS 12.2.1

## Diagnostics and log bundle

```
Upgrading management cluster 'tanzu-mgmt' to TKG version 'v1.5.0-tf-v0.10.1' with Kubernetes version 'v1.21.5+vmware.1'. Are you sure? [y/N]: y
cluster specific secret is not present, fallback on bootstrap credential secret
Upgrading management cluster providers...
Checking cert-manager version...
Deleting cert-manager Version="v0.11.0"
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Performing upgrade...
Deleting Provider="cluster-api" Version="" TargetNamespace="capi-system"
Installing Provider="cluster-api" Version="v0.3.23" TargetNamespace="capi-system"
Deleting Provider="bootstrap-kubeadm" Version="" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-bootstrap-system"
Deleting Provider="control-plane-kubeadm" Version="" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.23" TargetNamespace="capi-kubeadm-control-plane-system"
Deleting Provider="infrastructure-vsphere" Version="" TargetNamespace="capv-system"
Installing Provider="infrastructure-vsphere" Version="v0.7.10" TargetNamespace="capv-system"
Management cluster providers upgraded successfully...
Upgrading management cluster kubernetes version...
updating additional components: 'addons-management/kapp-controller' ...
updating additional components: 'addons-management/tanzu-addons-manager' ...
updating additional components: 'tkr/tkr-controller' ...
updating additional components: 'addons-management/core-package-repo' ...
Verifying kubernetes version...
Retrieving configuration for upgrade cluster...
Create InfrastructureTemplate for upgrade...
Upgrading control plane nodes...
Patching KubeadmControlPlane with the kubernetes version v1.21.5+vmware.1...
Skipping KubeadmControlPlane patch as kubernetes versions are already same v1.21.5+vmware.1
Waiting for kubernetes version to be updated for control plane nodes
Upgrading worker nodes...
Patching MachineDeployment with the kubernetes version v1.21.5+vmware.1...
Skipping MachineDeployment patch as kubernetes versions are already same v1.21.5+vmware.1
Waiting for kubernetes version to be updated for worker nodes...
updating additional components: 'metadata/tkg' ...
updating additional components: 'addons-management/standard-package-repo' ...
Error: unable to upgrade management cluster: failed to update metadata configmaps after kubernetes upgrade: error while upgrading additional component 'addons-management/standard-package-repo': kubectl apply failed, output: error: no objects passed to apply
: exit status 1
Usage:
  tanzu management-cluster upgrade [flags]

Examples:
  
  # Upgrade a management cluster
  tanzu management-cluster upgrade

  # Upgrade a management cluster using specific os name (vsphere)
  tanzu management-cluster upgrade mc-1 --os-name photon

  # Upgrade a management cluster using specific os name and version
  tanzu management-cluster upgrade mc-1 --os-name ubuntu --os-version 20.04

  # Upgrade a management cluster using specific os name, version and arch
  tanzu management-cluster upgrade mc-1 --os-name ubuntu --os-version 20.04 --os-arch amd64

  [+] : Options available for: os-name, os-version, os-arch are as follows:
  vSphere: 
    --os-name ubuntu --os-version 20.04 --os-arch amd64
    --os-name photon --os-version 3 --os-arch amd64	
  aws: 
    --os-name ubuntu --os-version 20.04 --os-arch amd64
    --os-name amazon --os-version 2 --os-arch amd64
  azure:
    --os-name ubuntu --os-version 20.04 --os-arch amd64
    --os-name ubuntu --os-version 18.04 --os-arch amd64


Flags:
  -h, --help                help for upgrade
      --os-arch string      OS arch to use during management cluster upgrade. Discovered automatically if not provided (See [+])
      --os-name string      OS name to use during management cluster upgrade. Discovered automatically if not provided (See [+])
      --os-version string   OS version to use during management cluster upgrade. Discovered automatically if not provided (See [+])
  -t, --timeout duration    Time duration to wait for an operation before timeout. Timeout duration in hours(h)/minutes(m)/seconds(s) units or as some combination of them (e.g. 2h, 30m, 2h30m10s) (default 30m0s)
  -y, --yes                 Upgrade management cluster without asking for confirmation

Global Flags:
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)

Error: exit status 1

✖  exit status 1 
```

### LINKED ISSUE #3277: Cluster upgrades don't work due to assumption of TKG standard repository
## Bug Report

All cluster upgrades for TCE will fail due to assumptions about a `addons-management/standard-package-repo` existing.

The error users will receive is as follows:

```
Error: unable to upgrade management cluster: failed to update metadata configmaps after kubernetes upgrade: error while upgrading additional component 'addons-management/standard-package-repo': kubectl apply failed, output: error: no objects passed to apply : exit status 1
```

### LINKED ISSUE #3319: Differentiation TKG/TCE from TMC needed in  Framework v0.11.1
While we are working on the TCE/TKG pin mode from TMC side, we found there is no field of TCE for TMC to tell whether it is TKG or TCE. This would be a blocker for TMC STARTER in march as currently the plan is to pin this to  Framework v0.11.1. 
Because without the differentiation, it will be an issue from support perspective that the SRE/GSS/Engineer team to provide different support for TKG and TCE. It will introduce confusion and support effort for engineering team. 
Without the ability to differentiate TCE from TKG then in the TMC API/CLI/UI a TCE set-up will display as a TKG mgmt/workload cluster. UX is bad here. 

Additional reference : https://github.com/vmware-tanzu/tanzu-framework/pull/1599
## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

### LINKED ISSUE #3363: Bump to framework `v0.11.2`
In order to support the v0.11.0 release of TCE, we need to bump to v0.11.2 to include:

* fixes to upgrade failures
* edition detection for cluster (to support TMC)

### LINKED ISSUE #3385: Framework `v0.11.2` has no proper means of setting the edition
This issue tracks:

* https://github.com/vmware-tanzu/tanzu-framework/issues/1797

Some plugins work in a context-aware manner. For example, the management cluster provides a different UI when the edition is `tce` vs `tkg`.

Framework `v0.11.2` is caught between updates where edition detection is moved around. When build framework, the `BUILD_EDITION` `LD_FLAG` no longer exists. You can see here the `BUILD_EDITION` is still looked up, but never used anywhere:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.2/common.mk#L31-L35

By default the `config.yaml` (client config) will always be structured as follows:

```yaml
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    bomRepo: projects-stg.registry.vmware.com/tkg
    compatibilityFilePath: framework-zshippable/tkg-compatibility
    discoverySources:
    - local:
        name: default-local
        path: standalone
    edition: tkg
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli-framework
        name: core
    unstableVersionSelector: none
  features:
    cluster:
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
    global:
      context-aware-cli-for-plugins: "true"
      package-based-lcm-beta: "false"
    management-cluster:
      aws-instance-types-exclude-arm: "true"
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
      export-from-confirm: "true"
      import: "false"
      network-separation-beta: "false"
      standalone-cluster-mode: "false"
kind: ClientConfig
metadata:
  creationTimestamp: null
```

Normally, it'd be possible to use tanzu config set cli.edition tce to set this, note:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.2/Makefile#L63

But it does not work in this version. You'll get:

```
$ tanzu config set cli.edition tce
Error: unsupported config path parameter [cli] (was expecting 'features.<plugin>.<feature>' or 'env.<env_variable>')

✖  unsupported config path parameter [cli] (was expecting 'features.<plugin>.<feature>' or 'env.<env_variable>')
```

If you add `features.` it puts the setting in the `features` section, but that does not fix the UI.

The only way to make this work is to manually edit the config file, which won't work for our users.

### PR DESCRIPTION
**Pull request by joshrosso**
## What this PR does / why we need it

Resolves: https://github.com/vmware-tanzu/community-edition/issues/3363

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Bump framework dependency to `v0.11.2`
```

### CODE REVIEW

**Comment by joshrosso** [comment]
This will be held as a draft until v0.11.2 is official tagged.

* https://github.com/vmware-tanzu/tanzu-framework/pull/1787

**Review by davidvonthenen — DISMISSED** [review]

**Comment by joshrosso** [comment]
This also solves: 

* https://github.com/vmware-tanzu/community-edition/issues/3319

**Comment by joshrosso** [comment]
@dvonthenen can I get one more review from you?

**Review by davidvonthenen — DISMISSED** [review]

**Comment by dvonthenen** [comment]
I was looking at this a little closer:
https://github.com/vmware-tanzu/community-edition/pull/3364/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R75

and it appears that we pushed the BUILD_EDITION from a variable and moved it directly into the build targets in a number of places:
https://github.com/vmware-tanzu/community-edition/blob/main/Makefile#L331
https://github.com/vmware-tanzu/community-edition/blob/main/Makefile#L284

Don't know if you want to delete this or replace using the variable your created.

**Comment by joshrosso** [comment]
> I was looking at this a little closer: https://github.com/vmware-tanzu/community-edition/pull/3364/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R75
> 
> and it appears that we pushed the BUILD_EDITION from a variable and moved it directly into the build targets in a number of places: https://github.com/vmware-tanzu/community-edition/blob/main/Makefile#L331 https://github.com/vmware-tanzu/community-edition/blob/main/Makefile#L284
> 
> Don't know if you want to delete this or replace using the variable you created.

I canoncalized the make file to pull from that single environment variable. thanks :+1:

**Review by davidvonthenen — APPROVED** [review]

**Pull request merged**
