### PR TITLE
`unmanaged-cluster`: Implements selecting packages from namespaces on `intstall-package`

### LINKED ISSUE #4165: [Unmanaged Cluster] - Enable installing packages (formerly "profiles") at creation from core repo
## Feature Request
Currently unless the package is in the tanzu-package-repo-global namespace, it cant be installed at creation time. this makes sense to be the default, but there should be a way to also specify a namespace. this is important for app-toolkit and TAP auto installs as secretgen is in the core repo meaning its in tkg-system and not tanzu-package-repo-global but it isnt installed by default.
this also lines with the issue i opened regarding adding the ability to add a repo to a specific namespace via the additionalRepos feature in which case this becomes even more important.

## Describe alternatives you've considered
to install packages after cluster creation and not via the new feature for auto installation

## Additional context
this effects currently any package that relies on secretgen when running on unmanaged clusters in 0.12.rc2 (Tanzu RabbitMQ, TAP, App Toolkit etc.)

### PR DESCRIPTION
**Pull request by jpmcb**
- Users can specify the following mapping with the --install-package flag: 
```
pkg-name:pkg-version:config-file-path:package-repo-namespace
```
- Also includes docs updates

## Which issue(s) this PR fixes
Fixes: #4165

## Describe testing done for PR
Built binary and able to run successfully

```
$ tanzu unmanaged-cluster create my-cluster secretgen:latest::tkg-system
```

Still able to run successfully

```
$ tanzu unmanaged-cluster create my-cluster fluent
```

### CODE REVIEW

**Comment by jpmcb** [comment]
cc @jorgemoralespou - would you be willing to try this out and give some feedback? 👀

**Comment by jorgemoralespou** [comment]
Sure thing

**Comment by jorgemoralespou** [comment]
Some feedback (See last one first):

1. Test for missing package and NON existing namespace  **OK**
   Input: 
   ```
   tanzu uc create test --install-package secretgen:::my-packages
   ```

   Output:
   ```
   Installing package secretgen
     WARNING: failed to install package secretgen. Error: no package was resolved for name secretgen with version
   ```
   No package with any secretgen in it is available in the repository. 

1. Test for package in repository with no version specified and NON existing namespace **KO**
   Input: 
   ```
   tanzu uc create test --install-package external-dns:::my-packages
   ```

   Output:
   ```
   Installing package external-dns
      WARNING: failed to install package external-dns. Error: no package was resolved for name external-dns with version
   ```
   Package exists in repository but latest version is not installed if version is missing. Help says: `package-name should be the fully qualified package name or a prefix to a package name found in an installed package repository. package-version is optional and resolves to the latest semantic versioned package if not specified or latest is entered.` 

1. Test for Fully Qualified package in repository with no version specified and NON existing namespace **KO**
   Input: 
   ```
   tanzu uc create test --install-package external-dns.community.tanzu.vmware.com:::my-packages
   ```

   Output:
   ```
   Installing package external-dns.community.tanzu.vmware.com
      WARNING: failed to install package external-dns.community.tanzu.vmware.com. Error: no package was resolved for name external-dns.community.tanzu.vmware.com with version
   ```
   Package exists in repository but latest version is not installed if version is missing. Help says: `package-name should be the fully qualified package name or a prefix to a package name found in an installed package repository. package-version is optional and resolves to the latest semantic versioned package if not specified or latest is entered.` 

1. Test for Fully Qualified package in repository with `latest` version specified and NON existing namespace **KO**
   Input: 
   ```
   tanzu uc create test --install-package external-dns.community.tanzu.vmware.com:::my-packages
   ```

   Output:
   ```
   Installing package external-dns.community.tanzu.vmware.com
      WARNING: failed to install package external-dns.community.tanzu.vmware.com. Error: no package was resolved for name external-dns.community.tanzu.vmware.com with version latest
   ```
   Package exists in repository but latest version is not installed if version is latest. Help says: `package-name should be the fully qualified package name or a prefix to a package name found in an installed package repository. package-version is optional and resolves to the latest semantic versioned package if not specified or latest is entered.` 

1. Test for Fully Qualified package in repository with `0.10.0` version specified and NON existing namespace **KO**
   Input: 
   ```
   tanzu uc create test --install-package external-dns:0.10.0::my-packages
   ```

   Output:
   ```
   Installing package external-dns.community.tanzu.vmware.com
   WARNING: failed to install package external-dns.community.tanzu.vmware.com. Error: no package was resolved for name external-dns.community.tanzu.vmware.com with version 0.10.0
   ```
   Package exists in repository but 0.10.0 version is not installed if version is specified. Help says: `package-name should be the fully qualified package name or a prefix to a package name found in an installed package repository. package-version is optional and resolves to the latest semantic versioned package if not specified or latest is entered.` 

1. Test for Fully Qualified package in repository with `0.10.0` version specified and existing namespace **OK**
   Input: 
   ```
   tanzu uc create test --install-package external-dns:0.10.0::default
   ```

   Output:
   ```
   Installing package external-dns.community.tanzu.vmware.com
      Selected package external-dns.community.tanzu.vmware.com
      Using package version 0.10.0
      Installing package with no configuration file
   ```
   Package installed successfully, so I take that trying to install in a non-existing namespace manifests as the wrong error.

**Comment by jpmcb** [comment]
Great feedback. I think that is all valid.

Is there a reason we wouldn't want to automatically create the namespace if it's not there? Probably cuts down on a few extra steps for users. And this is something that many packages already do.

We could log a warning to the user that a new namespace is being created just to surface what's happening.

**Comment by vrabbi** [comment]
Having the nameapace be created would be great. I havr a few use cases of packages that docs say should be installed in a specific named namespace but that namespace is not pre created in a cluster. Similar functionality to the --create-namespace flag that exists for the package commands in tanzu cli and it would just make the UX better.

**Pull request closed without merging**
