### PR TITLE
Add AWS deployment automation for management cluster and modularize the scripts used

### LINKED ISSUE #906: E2E automation scripts: Modularize the scripts we currently have
Currently we have a lot of scripts for E2E tests for AWS and Docker standalone / managed clusters. We can modularize some of the parts of the scripts into separate scripts. For example -

- Setting up a cluster - commands are all the same, just different cluster config for different platforms
- Testing Gatekeeper package - this test can be done regardless of any platform - AWS/Docker/Azure etc
- Tearing down clusters - this is common too for platforms

We have already modularized stuff like building and installing TCE, so that's all good

We can look for more places where we can modularize and reuse code whenever possible, so that changes are easier to make with less duplication

### PR DESCRIPTION
**Pull request by rajaskakodkar**
## What this PR does / why we need it

This PR adds AWS deployment automation for management cluster and modularizes the scripts we have for deployment automation for different providers.

Listing the significant changes here:
1. Replaced `e2e-test` target in Makefile with `tce-aws-managed-cluster-e2e-test` and added `tce-aws-standalone-cluster-e2e-test`
2. Replaced  `e2e-all-tests` workflow in Github Actions with `e2e-tce-aws-managed-cluster` and added `e2e-tce-aws-standalone-cluster`
3. Replaced `standalone-template.yaml` with `cluster-config.yaml` and dropped AWS related env variables from the yaml since they are already exported in the env.
4. `test/aws/deploy-tce.sh` is split into `test/aws/deploy-tce-managed.sh` and `test/aws/deploy-tce-standalone.sh` with the respective commands to build tce, create clusters, run test and then tear down clusters
5. Added `test/aws/e2e-test.sh` with the commands to run e2e test for gatekeeper. This can now be re-used in deployment automation for other providers
6. Decoupled and modularized other scripts and made required changes in ` test/vsphere/run-tce-vsphere-standalone-cluster.sh`
## Details for the Release Notes

```release-note
Add AWS deployment automation for management clusters 
```

## Which issue(s) this PR fixes

Fixes: #906 

## Describe testing done for PR

Ran `make check`
Tested the changes on my fork and here are the logs
Management cluster - https://github.com/rajaskakodkar/community-edition/runs/3487690266?check_suite_focus=true
Standalone cluster - https://github.com/rajaskakodkar/community-edition/runs/3487690349?check_suite_focus=true
TCE tag appears as v0.6.0-dev.1 in the logs and its because my branch did not have tags from upstream.

### CODE REVIEW

**Review by navidshaikh — CHANGES_REQUESTED** [review]
thanks!

left a few suggestions about organising different logical blocks into functions

**Review by davidvonthenen — COMMENTED** [review]
Got some feedback.... most are just general questions to understand what is going on. This look great!

**Review by davidvonthenen — APPROVED** [review]
I just have the comment here:
https://github.com/vmware-tanzu/community-edition/pull/1523#discussion_r700522250

which was answered offline! thanks!

Otherwise LGTM

**Review by karuppiah7890 — CHANGES_REQUESTED** [review]

**Review by karuppiah7890 — CHANGES_REQUESTED** [review]

**Review by navidshaikh — APPROVED** [review]
added a few suggestions which can be taken care in follow ups, overall looks good to me!

**Review by karuppiah7890 — APPROVED** [review]

**Pull request merged**
