### PR TITLE
Global doc: change Amazon EC2 to AWS

### LINKED ISSUE #1824: Remove uses of `Amazon EC2` with `Amazon Web Services` or `AWS` where appropriate
## Description

We should move away from all refernces to provider integrations with AWS as `Amazon EC2`. Amazon EC2 is only the compute aspect of AWS and does not take into consideration the other areas we integrate with, such as VPC.

## Location

This applies to the entire docs site.

## Additional Context

None

### PR DESCRIPTION
**Pull request by kcoriordan**
Signed-off-by: kcoriordan <koriordan@vmware.com>

## What this PR does / why we need it
Changes Amazon EC2 to Amazon Web Services on the first occurrence (excluding headings) and AWS for subsequent occurrences. 

I will do the toc in a separate PR. 
Related: #1821

## Details for the Release Notes (PLEASE PROVIDE)

```NONE

```

## Which issue(s) this PR fixes

* Fixes: https://github.com/vmware-tanzu/community-edition/issues/1824

### CODE REVIEW

**Review by stmcginnis — COMMENTED** [review]
Looks good. I see EC2 referenced a few other places. Some may be legitimate where they are specifically talking about EC2 compute topics, but things like `latest-toc.yml` may something that should be updated to just AWS.

Some files we may want to double check:

```sh
addons/packages/harbor/2.2.3/README.md
docs/site/content/docs/latest/configure-id-mgmt.md
docs/site/content/docs/latest/deploy.md
docs/site/content/docs/latest/register_tmc.md
docs/site/content/docs/latest/ref-vsphere.md
docs/site/content/docs/latest/verify-deployment.md
docs/site/content/docs/latest/ref-aws.md
docs/site/content/docs/assets/support-matrix.md
docs/site/content/docs/latest/support-matrix.md
docs/site/content/docs/latest/delete-cluster.md
docs/site/data/docs/latest-toc.yml
```

**Review by jpmcb — CHANGES_REQUESTED** [review]
We should still be explicit about using EC2 keypairs. Otherwise, users will get confused and won't know what we are referencing. Seem comments made here for further context

https://github.com/vmware-tanzu/tanzu-framework/pull/657#discussion_r713120319

**Review by joshrosso — CHANGES_REQUESTED** [review]
added a few more spots I _believe_ we want to clean up.

**Review by stmcginnis — CHANGES_REQUESTED** [review]

**Review by stmcginnis — APPROVED** [review]
This looks good. There's one formatting issue since we don't lint the "asset" files, but it should render fine. We would just have to address if we ever figure out how to lint those files properly.

Will approve and leave it up to you if you want to merge or fix up that one. I think it's fine to just merge though.

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
