### PR TITLE
Removes mention of cgroups v1 being a requirement in docs

### LINKED ISSUE #3516: Remove mentions of cgroups/docker desktop versions for TCE `v0.11.0`
`v0.11.0` fixes the cgroups (#2798) issue.

In our install and getting started guides, we can remove the requirements mentioning:

* using cgroupsv1
* used versions of docker <= 4.2.0

### PR DESCRIPTION
**Pull request by jpmcb**
## What this PR does / why we need it
Removes mention of cgroups v1 from docs (which has been fixed in upcoming `v0.11.0`)

## Which issue(s) this PR fixes
Fixes: #3516

## Describe testing done for PR
`hugo serve` and `make lint`

### CODE REVIEW

**Review by stmcginnis — DISMISSED** [review]
Looks good. Will need to backport to `release-0.11` for these changes to show up in the v0.11.0 docs.

**Comment by stmcginnis** [comment]
Shoot, looks like there is a merge conflict now with `docs/site/content/docs/latest/support-matrix.md`.

**Review by kcoriordan — DISMISSED** [review]

**Comment by jpmcb** [comment]
> Will need to backport to `release-0.11` for these changes to show up in the `v0.11.0` docs.

Do I need to cherry pick this over to that branch as well?

**Comment by stmcginnis** [comment]
> Do I need to cherry pick this over to that branch as well?

Yep, now that we have versioned docs, any changes for a given release need to be in the `release-xx` branch. Things normally will be there through normal development, but we have the window between when the RC is cut and the final release is done when we've created the `release-xx` branch in preparation for the release. Since we've created `release-0.11`, for these changes to show up in the v0.11.0 docs, the change will need to merge to `main`, then be cherry picked over to the release branch.

**Review by stmcginnis — APPROVED** [review]

**Pull request merged**
