### PR TITLE
[Chocolatey] Upgrade test for chocolatey Package

### LINKED ISSUE #2231: Automated upgrade test for Chocolatey package as part of PR changes
## Feature Request

Same as #2229 , but just for upgrade. Upgrade has been mentioned in #2229 but it cannot be done as part of #2229 as of now since TCE is not published to the Chocolatey Community Repository

The upgrade check would look something like
- Install from the public package repo containing TCE stable release
- Upgrade using the local package repo containing TCE package with the PR changes

I think this upgrade test will only work when there is a version change in the TCE Chocolatey package. In case of other changes (install script changes, uninstall script changes etc), we have to see if we can do this upgrade test. Or we can try to do some sort of reinstall if not upgrade, in such cases. We have to think this through though

## Describe alternatives you've considered

None, except for manual testing

### PR DESCRIPTION
**Pull request by aman556**
## What this PR does / why we need it

This PR is adding upgrade test for chocolatey Package
- Upgrade test is first running hack/choco/test/e2e-test.ps1
  for current stable TCE version
- Then it is updating version and SHA values for new release and
  performing e2e test for it.

Signed-off-by: Aman Sharma <amansh@vmware.com>
## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: [#2231](https://github.com/vmware-tanzu/community-edition/issues/2231)

## Describe testing done for PR

Create a release in fork branch whose logs are [here](https://github.com/aman556/community-edition/runs/5314785268?check_suite_focus=true)

### CODE REVIEW

**Review by davidvonthenen — COMMENTED** [review]
Hi @aman556 

I just wanted to double check with you... this looks like this handles a test for upgrading TCE from the current version to the new version, correct? If so, I do have some questions:

- where is the automation that performs publish to https://chocolatey.org/ ? As described in this issue: https://github.com/vmware-tanzu/community-edition/issues/3178
- after the publish in the previous item is performed, does this handle the timing for the publish to happen to https://chocolatey.org/ and the availability to upgrade? In other words, if the trigger for this is the release getting published, we need to make sure that the publish to https://chocolatey.org/ has completed successfully before attempting to run the upgrade scenario

**Comment by aman556** [comment]
Hello @dvonthenen,
Thanks for following up. Sorry I missed  [#3178](https://github.com/vmware-tanzu/community-edition/issues/3178) will surely try to modify the script as per requirement.

**Comment by aman556** [comment]
Please refer https://github.com/vmware-tanzu/community-edition/issues/3178#issuecomment-1050619262 for how I am planning the workflow.

**Comment by nrb** [comment]
Could this file replace the bash update script? It looks like we're producing the same logic in 2 different spots/languages, which could lead to one spot getting missed should the code change.

This one seems to be a better candidate for keeping to me, since it actually verifies that the changes produce an installable package and provides a log for it.

**Comment by aman556** [comment]
Hello @nrb Yeah it can replace the update version and and we can also avoid a shell script format file in choco(which is for windows). As there were two issues by @karuppiah7890 so maybe he has something in his mind for two different files. @karuppiah7890 can you please have a look on this script and share your POV?

The Pros I can see for going only with this script is that it is testing so we can go with merging in main directly without any test/check as this script is only handling that and same we can do for homebrew   by running [check-tce-homebrew-formula.sh](https://github.com/vmware-tanzu/homebrew-tanzu/blob/main/test/check-tce-homebrew-formula.sh) before and after the changes in [update-homebrew-package.sh)](https://github.com/vmware-tanzu/community-edition/blob/main/hack/homebrew/update-homebrew-package.sh)

**Comment by karuppiah7890** [comment]
Sure, let's go ahead with a powershell script to update the version and also to test it. Let's get rid of the bash script 👍

**Comment by aman556** [comment]
hey @nrb I tried to modify the ps1 script to update version for choco but for `git push` we need to convert URL to SSH which we need to create a SSH key pair for tce-automation account and some additional stuff to so I am thinking to hold this script for testing `choco upgrade`

**Comment by dvonthenen** [comment]
> hey @nrb I tried to modify the ps1 script to update version for choco but for `git push` we need to convert URL to SSH which we need to create a SSH key pair for tce-automation account and some additional stuff to so I am thinking to hold this script for testing `choco upgrade`

If this is on a "admin" related workflow (ie like a tag, release draft creation, release publish, etc), you can use the release token and continue to use https. Example here:
https://github.com/vmware-tanzu/community-edition/blob/main/.github/workflows/release-ga.yaml#L122-L128

**Comment by aman556** [comment]
Thanks @dvonthenen for mentioning above resources so I have did the same things and tested in my fork repo so in window github runner the PR is failing with authentication failure https://github.com/aman556/community-edition/runs/5406518928?check_suite_focus=true so after searching a bit I found a solution that in windows we have to use SSH repo URL instead of https for which we need key pairs. 
I haven’t used `ACTUAL_COMMIT_SHA: ${{ github.sha }}` in env and don’t know what basically it is for will see it’s use and try it in my workflow.

**Comment by dvonthenen** [comment]
> I haven’t used `ACTUAL_COMMIT_SHA: ${{ github.sha }}` in env and don’t know what basically it is for will see it’s use and try it in my workflow.

I was just highlighting the entire github action. You shouldnt have a need for that value.

> Thanks @dvonthenen for mentioning above resources so I have did the same things and tested in my fork repo so in window github runner the PR is failing with authentication failure https://github.com/aman556/community-edition/runs/5406518928?check_suite_focus=true so after searching a bit I found a solution that in windows we have to use SSH repo URL instead of https for which we need key pairs.

I think you misunderstand, I think if you replace the URI here:
https://github.com/vmware-tanzu/community-edition/pull/3242/files#diff-8b3186bc5dc368597b01fa21fbab3d777cdf59ecdf889d81a453f2f73333881cR17

With this:
`https://git:$GITHUB_TOKEN@github.com`

That should give you the ability to create a PR, write, etc without needing an SSH key.

**Comment by aman556** [comment]
Hey @dvonthenen I get you what you said and while writing https://github.com/vmware-tanzu/community-edition/pull/3242#issuecomment-1058132823 I already tested using workflow in my fork branch by creating a release. The scripts are 
-  [Work flow](https://github.com/aman556/community-edition/blob/test-choco-automation-workflow/.github/workflows/release-choco-package.yaml) 
- [hoco-upgrade-test.ps1)](https://github.com/aman556/community-edition/blob/test-choco-automation-workflow/hack/choco/test/choco-upgrade-test.ps1)

So while running the above workflow I am facing authentication issue and got to know that in windows workflow things are different then ubuntu and mac

**Comment by dvonthenen** [comment]
> Hey @dvonthenen I get you what you said and while writing [#3242 (comment)](https://github.com/vmware-tanzu/community-edition/pull/3242#issuecomment-1058132823) I already tested using workflow in my fork branch by creating a release. The scripts are
> 
> * [Work flow](https://github.com/aman556/community-edition/blob/test-choco-automation-workflow/.github/workflows/release-choco-package.yaml)
> * [hoco-upgrade-test.ps1)](https://github.com/aman556/community-edition/blob/test-choco-automation-workflow/hack/choco/test/choco-upgrade-test.ps1)
> 
> So while running the above workflow I am facing authentication issue and got to know that in windows workflow things are different then ubuntu and mac

Ok, I misunderstood. Missed that you already tried this. Going to take a look about getting going for you.

**Comment by dvonthenen** [comment]
> Will private message you the details.

PM the information for ssh. Waiting for status.

**Comment by aman556** [comment]
inserted SSH authentication in code but due to irregularities in workflow can't able to test in fork will try to finish it on monday once come back from PTO.

**Comment by dvonthenen** [comment]
Going to approve and merge this and will work off this as the base

**Review by davidvonthenen — APPROVED** [review]

**Pull request merged**
