### PR TITLE
moving doc files from /latest to /docs

### LINKED ISSUE #882: Introduce versioning of documentation site to TCE
Some of what's involved for how Velero does it:
https://velero.io/docs/v1.6/release-instructions/#changelog-and-docs-pr
https://github.com/vmware-tanzu/velero/blob/main/Makefile#L351-L361
https://github.com/vmware-tanzu/velero/blob/main/hack/release-tools/gen-docs.sh#L48

### PR DESCRIPTION
**Pull request by kcoriordan**
Signed-off-by: kcoriordan <koriordan@vmware.com>

## What this PR does / why we need it
-Moved all files & folders  from /`latest` to /`docs` and updated links accordingly
-added v0.10 to `docs_versions ` and ` docs_latest ` in `config.yaml`
-created `v0.10-toc.yml`
-added mapping between v0.10 and v0.10-toc in `toc-mapping.yml`
-In `partials/header.html` - in row 11, 25 - replaced `$latest ` with `$.Site.Params.docs_latest`
-In `netlify.toml,` in row 3 added  `make production-build` command, in row 18, added `make preview-build`  command
-In `Makefile `added preview build command in row 10  

related to: #3490 
## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #882

### CODE REVIEW

**Comment by jonasrosland** [comment]
Talked to Kay on Zoom, minor changes needed and will continue work and hopefully finalize on Monday morning next week.

**Comment by jonasrosland** [comment]
This is starting to look good. I have now locked the Netlify deploy to the latest build at March 18th, so once this is merged we need @stmcginnis to help with backporting these changes to the `release-0.10` branch, and perhaps also the 0.11 one.

**Comment by stmcginnis** [comment]
We may need to just ignore the urllint job failure for now until the docs updates are in place that provide those pages.

**Review by stmcginnis — APPROVED** [review]
Looks good. Will get this into our release branches, then we can get the updated docs published.

**Pull request merged**
