### PR TITLE
Enables dependabot version upgrade

### PR DESCRIPTION
**Pull request by jpmcb**
## What this PR does / why we need it
This yaml config should enable dependabot version upgrades for our many go modules. This will open bot PRs for upgradeable dependencies in our go mods.

As documented here: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Enables dependabot PRs
```

## Which issue(s) this PR fixes
N/a

## Describe testing done for PR
Will have to wait and see it work in GitHub 👀 

## Special notes for your reviewer
N/a

### CODE REVIEW

**Comment by nrb** [comment]
Should we exclude tanzu-framework, since we know we're not going to be actively updating to every new version?

**Comment by jpmcb** [comment]
> Should we exclude tanzu-framework

That's a good point. Especially since we update those manually for our releases. Looking at a way to ignore those now

**Review by stmcginnis — APPROVED** [review]
This looks good to me. Will wait to merge in case anyone else wants to take a look, but I think we can just address any issues in follow up patches.

**Comment by nrb** [comment]
Yeah, let's merge and see what shakes out :)

**Pull request merged**
