### PR TITLE
Remove unnecessary namespaces from package yaml files

### LINKED ISSUE #936: Packages should not be installed in the package namespace, but rather in the global namespace
## Bug Report
In default packagerepository after 0.6.0, Packages and PackageMetadata are targetting the namespace of the package (e.g. contour package is expected to live in contour namespace, which does not exist). Packages should target a namespace that exists, and for those that come with TCE, they are expected to be installed in the global namespace: https://carvel.dev/kapp-controller/docs/latest/packaging/#namespacing
And to verify with @cppforlife if in 0.20.0-cr.2 namespaces for these resources should be defined or not, per internal discussions.

## Expected Behavior
That the packagerepository can make the packages that provides available in the cluster. Currently, they fail to be available.

## Steps to Reproduce the Bug
Install a 0.6.0 cluster, update to use kapp-controller 0.20.0-rc1 and deploy the tce repository with latest tag (as stable has not been yet tag because TCE still provides 0.18.alpha4 kapp-controller).

### LINKED ISSUE #1054: remove unnecessary metadata.namespace from PackageMetadata/Package CRs
## Feature Request

Currently Package and PackageMetadata CRs include metadata.namespace. there is no need to specify them (and in fact it's dropped by kapp-controller):

- https://github.com/vmware-tanzu/tce/blob/8f7e0f71671b8fb32e21ea70135ebb04e1524617/addons/packages/cert-manager/metadata.yaml#L5
- https://github.com/vmware-tanzu/tce/blob/8f7e0f71671b8fb32e21ea70135ebb04e1524617/addons/packages/cert-manager/1.3.1/package.yaml#L5

### PR DESCRIPTION
**Pull request by seemiller**
## What this PR does / why we need it

Remove unnecessary namespaces from package yaml files

## Which issue(s) this PR fixes

Fixes: #1054

## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by akodali18 — DISMISSED** [review]
lgtm for prometheus/grafana/fluent-bit

**Review by ankeesler — DISMISSED** [review]

**Review by nrb — DISMISSED** [review]

**Review by jpmcb — DISMISSED** [review]
`local-path-storage` LGTM

**Review by heww — DISMISSED** [review]

**Review by skriss — DISMISSED** [review]
approving for contour + contour-operator

**Review by tylerschultz — DISMISSED** [review]

**Review by carlisia — DISMISSED** [review]

**Review by XudongLiuHarold — DISMISSED** [review]
LGTM for `ako-operator` and `load-balancer-and-ingress-service`

**Review by nicolehanjing — DISMISSED** [review]

**Pull request merged**
