### PR TITLE
Docs: Update image paths for Getting Started page

### PR DESCRIPTION
**Pull request by garrying**
Signed-off-by: Garry Ing <ging@vmware.com>

## What this PR does / why we need it
This fixes an issue with images on `/docs/[[version]]/getting-started/` not loading. The issue can be seen here: https://tanzucommunityedition.io/docs/v0.11/getting-started/

## Which issue(s) this PR fixes

Fixes: n/a

## Describe testing done for PR
- `make production-build`
- `hugo serve`
- Navigate to `/docs/v0.11/getting-started/`
- Note: I had to change `load-docs.sh` to point to my fork/branch in order to see my changes

### CODE REVIEW

**Review by stmcginnis — COMMENTED** [review]
I don't believe this will work with the rendered site. It will show up OK in the GitHub view, but fail to find it in Hugo/Netlify.

**Comment by garrying** [comment]
I'm not super sure on how the site is being built on Netlify. Maybe @jonasrosland you have some guidance on paths for images?

**Comment by garrying** [comment]
Just realized there are related issues: #4084, #4126

**Comment by kcoriordan** [comment]
Approving, this is how the file path is handled in https://tanzucommunityedition.io/docs/v0.11/architecture/ and that's working ok.

**Review by kcoriordan — APPROVED** [review]

**Pull request merged**
