### PR TITLE
One Stop Shop to Change Tanzu Framework Version

### PR DESCRIPTION
**Pull request by davidvonthenen**
## What this PR does / why we need it

This PR makes it so you can change (or bump) the Tanzu Framework version while simultaneously testing to make sure TCE will build. Everything in the Makefile is now triggered by making a change to `hack/FRAMEWORK_BUILD_VERSION`.

In order to bump and test the new TF version:
1. `echo "vX.Y.Z" | tee ./hack/FRAMEWORK_BUILD_VERSION`
2. `make release`

The process of running the `make release` will call `prep-build-cli` just before building the plugins. In that target, the new code will replace/bump everything to the new Framework version and call `go mod tidy` to update the sum files. What you are left with are the changes needed for your PR to "bump" TF.

If the build fails, there is some additional work that needs to be done (to include in your PR) in order for `make release` to succeed and subsequently bump TF.

## Which issue(s) this PR fixes

Addresses: https://github.com/vmware-tanzu/community-edition/issues/3621

## Describe testing done for PR

Ran the steps outlined above!

## Special notes for your reviewer

NA

### CODE REVIEW

**Comment by dvonthenen** [comment]
After running `make release`:
```
[vonthd@rocky8 community-edition]$ git status
On branch feature/dynamictfversion
Your branch is up to date with 'origin/feature/dynamictfversion'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   cli/cmd/plugin/diagnostics/go.mod
	modified:   cli/cmd/plugin/diagnostics/go.sum
	modified:   hack/FRAMEWORK_BUILD_VERSION
	modified:   hack/builder/go.mod
	modified:   hack/builder/go.sum
```

And leaving out some of the gory details:
```
diff --git a/cli/cmd/plugin/diagnostics/go.mod b/cli/cmd/plugin/diagnostics/go.mod
index d5298d49..56b42c75 100644
--- a/cli/cmd/plugin/diagnostics/go.mod
+++ b/cli/cmd/plugin/diagnostics/go.mod
@@ -11,57 +11,141 @@ require (
 	github.com/vladimirvivien/gexe v0.1.1
 	github.com/vmware-tanzu/community-edition v0.9.1
 	github.com/vmware-tanzu/crash-diagnostics v0.3.7
-	github.com/vmware-tanzu/tanzu-framework v0.10.1
+	github.com/vmware-tanzu/tanzu-framework v0.11.3
 	sigs.k8s.io/kind v0.12.0
 )
 
 require (
 	cloud.google.com/go v0.99.0 // indirect
 	cloud.google.com/go/storage v1.10.0 // indirect
+	github.com/Azure/azure-sdk-for-go v58.1.0+incompatible // indirect
+	github.com/Azure/go-autorest v14.2.0+incompatible // indirect
+	github.com/Azure/go-autorest/autorest v0.11.21 // indirect
+	github.com/Azure/go-autorest/autorest/adal v0.9.16 // indirect
+	github.com/Azure/go-autorest/autorest/azure/auth v0.5.8 // indirect
+	github.com/Azure/go-autorest/autorest/azure/cli v0.4.2 // indirect
+	github.com/Azure/go-autorest/autorest/date v0.3.0 // indirect
+	github.com/Azure/go-autorest/autorest/to v0.4.0 // indirect
+	github.com/Azure/go-autorest/autorest/validation v0.3.1 // indirect
+	github.com/Azure/go-autorest/logger v0.2.1 // indirect
+	github.com/Azure/go-autorest/tracing v0.6.0 // indirect
 	github.com/BurntSushi/toml v0.4.1 // indirect
+	github.com/MakeNowJust/heredoc v1.0.0 // indirect
+	github.com/Masterminds/semver v1.5.0 // indirect
+	github.com/Microsoft/go-winio v0.5.0 // indirect
+	github.com/PuerkitoBio/purell v1.1.1 // indirect
+	github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578 // indirect
 	github.com/adrg/xdg v0.2.1 // indirect
 	github.com/alessio/shellescape v1.4.1 // indirect
+	github.com/apparentlymart/go-cidr v1.1.0 // indirect
+	github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d // indirect
 	github.com/aunum/log v0.0.0-20200821225356-38d2e2c8b489 // indirect
 	github.com/beorn7/perks v1.0.1 // indirect
+	github.com/blang/semver v3.5.1+incompatible // indirect
 	github.com/cespare/xxhash/v2 v2.1.2 // indirect
+	github.com/cheggaaa/pb v1.0.29 // indirect
+	github.com/containerd/containerd v1.5.7 // indirect
+	github.com/containerd/stargz-snapshotter/estargz v0.7.0 // indirect
+	github.com/coredns/caddy v1.1.1 // indirect
+	github.com/coredns/corefile-migration v1.0.13 // indirect
+	github.com/cppforlife/cobrautil v0.0.0-20200514214827-bb86e6965d72 // indirect
+	github.com/cppforlife/color v1.9.1-0.20200716202919-6706ac40b835 // indirect
+	github.com/cppforlife/go-cli-ui v0.0.0-20200716203538-1e47f820817f // indirect
 	github.com/davecgh/go-spew v1.1.1 // indirect
+	github.com/dimchansky/utfbom v1.1.1 // indirect
+	github.com/docker/cli v20.10.7+incompatible // indirect
+	github.com/docker/distribution v2.7.1+incompatible // indirect
+	github.com/docker/docker v20.10.9+incompatible // indirect
+	github.com/docker/docker-credential-helpers v0.6.3 // indirect
+	github.com/docker/go-connections v0.4.0 // indirect
+	github.com/docker/go-units v0.4.0 // indirect
+	github.com/drone/envsubst/v2 v2.0.0-20210730161058-179042472c46 // indirect
 	github.com/evanphx/json-patch v4.11.0+incompatible // indirect
 	github.com/evanphx/json-patch/v5 v5.6.0 // indirect
 	github.com/fatih/color v1.13.0 // indirect
 	github.com/fsnotify/fsnotify v1.5.1 // indirect
 	github.com/ghodss/yaml v1.0.0 // indirect
 	github.com/go-logr/logr v0.4.0 // indirect
+	github.com/go-openapi/analysis v0.19.5 // indirect
+	github.com/go-openapi/errors v0.19.2 // indirect
+	github.com/go-openapi/jsonpointer v0.19.5 // indirect
+	github.com/go-openapi/jsonreference v0.19.5 // indirect
+	github.com/go-openapi/loads v0.19.4 // indirect
+	github.com/go-openapi/runtime v0.19.4 // indirect
+	github.com/go-openapi/spec v0.19.5 // indirect
+	github.com/go-openapi/strfmt v0.19.5 // indirect
+	github.com/go-openapi/swag v0.19.14 // indirect
+	github.com/go-openapi/validate v0.19.8 // indirect
+	github.com/go-stack/stack v1.8.0 // indirect
+	github.com/gobuffalo/flect v0.2.3 // indirect
 	github.com/gogo/protobuf v1.3.2 // indirect
+	github.com/golang-jwt/jwt/v4 v4.0.0 // indirect
 	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
 	github.com/golang/protobuf v1.5.2 // indirect
+	github.com/golang/snappy v0.0.3 // indirect
 	github.com/google/go-cmp v0.5.6 // indirect
+	github.com/google/go-containerregistry v0.6.0 // indirect
+	github.com/google/go-github/v33 v33.0.0 // indirect
+	github.com/google/go-querystring v1.1.0 // indirect
 	github.com/google/gofuzz v1.2.0 // indirect
 	github.com/google/uuid v1.3.0 // indirect
 	github.com/googleapis/gax-go/v2 v2.1.1 // indirect
 	github.com/googleapis/gnostic v0.5.5 // indirect
+	github.com/hashicorp/go-version v1.3.0 // indirect
+	github.com/hashicorp/hcl v1.0.0 // indirect
 	github.com/imdario/mergo v0.3.12 // indirect
 	github.com/inconshreveable/mousetrap v1.0.0 // indirect
+	github.com/josharian/intern v1.0.0 // indirect
 	github.com/json-iterator/go v1.1.12 // indirect
+	github.com/juju/fslock v0.0.0-20160525022230-4d5c94c67b4b // indirect
+	github.com/k14s/imgpkg v0.17.0 // indirect
+	github.com/k14s/kbld v0.31.0 // indirect
+	github.com/k14s/semver/v4 v4.0.1-0.20210701191048-266d47ac6115 // indirect
+	github.com/k14s/starlark-go v0.0.0-20200720175618-3a5c849cc368 // indirect
+	github.com/k14s/ytt v0.32.1-0.20210511155130-214258be2519 // indirect
+	github.com/klauspost/compress v1.13.0 // indirect
 	github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de // indirect
+	github.com/magiconair/properties v1.8.5 // indirect
+	github.com/mailru/easyjson v0.7.6 // indirect
 	github.com/mattn/go-colorable v0.1.12 // indirect
 	github.com/mattn/go-isatty v0.0.14 // indirect
+	github.com/mattn/go-runewidth v0.0.13 // indirect
 	github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369 // indirect
+	github.com/mitchellh/go-homedir v1.1.0 // indirect
+	github.com/mitchellh/mapstructure v1.4.2 // indirect
 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
 	github.com/modern-go/reflect2 v1.0.2 // indirect
+	github.com/onsi/gomega v1.16.0 // indirect
+	github.com/opencontainers/go-digest v1.0.0 // indirect
+	github.com/opencontainers/image-spec v1.0.1 // indirect
 	github.com/pelletier/go-toml v1.9.4 // indirect
 	github.com/pkg/errors v0.9.1 // indirect
 	github.com/prometheus/client_golang v1.11.0 // indirect
 	github.com/prometheus/client_model v0.2.0 // indirect
-	github.com/prometheus/common v0.29.0 // indirect
-	github.com/prometheus/procfs v0.6.0 // indirect
+	github.com/prometheus/common v0.31.1 // indirect
+	github.com/prometheus/procfs v0.7.3 // indirect
+	github.com/rivo/uniseg v0.2.0 // indirect
 	github.com/sirupsen/logrus v1.8.1 // indirect
+	github.com/spf13/afero v1.6.0 // indirect
+	github.com/spf13/cast v1.4.1 // indirect
+	github.com/spf13/jwalterweatherman v1.1.0 // indirect
 	github.com/spf13/pflag v1.0.5 // indirect
+	github.com/spf13/viper v1.9.0 // indirect
+	github.com/subosito/gotenv v1.2.0 // indirect
+	github.com/vito/go-interact v0.0.0-20171111012221-fa338ed9e9ec // indirect
+	github.com/vmware-tanzu/carvel-kapp-controller v0.25.0 // indirect
+	github.com/vmware-tanzu/carvel-vendir v0.23.0 // indirect
+	github.com/vmware/govmomi v0.27.1 // indirect
+	github.com/yalp/jsonpath v0.0.0-20180802001716-5cc68e5049a0 // indirect
+	go.mongodb.org/mongo-driver v1.1.2 // indirect
 	go.opencensus.io v0.23.0 // indirect
 	go.starlark.net v0.0.0-20201006213952-227f4aabceb5 // indirect
-	golang.org/x/net v0.0.0-20210813160813-60bc85c4be6d // indirect
+	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 // indirect
+	golang.org/x/net v0.0.0-20211005215030-d2e5035098b3 // indirect
 	golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8 // indirect
+	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
 	golang.org/x/sys v0.0.0-20211205182925-97ca703d548d // indirect
-	golang.org/x/term v0.0.0-20210615171337-6886f2dfbf5b // indirect
+	golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
 	golang.org/x/text v0.3.7 // indirect
 	golang.org/x/time v0.0.0-20210723032227-1f47c861a9ac // indirect
 	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
@@ -72,6 +156,7 @@ require (
 	google.golang.org/grpc v1.42.0 // indirect
 	google.golang.org/protobuf v1.27.1 // indirect
 	gopkg.in/inf.v0 v0.9.1 // indirect
+	gopkg.in/ini.v1 v1.63.2 // indirect
 	gopkg.in/yaml.v2 v2.4.0 // indirect
 	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
 	k8s.io/api v0.22.2 // indirect
@@ -79,10 +164,16 @@ require (
 	k8s.io/apimachinery v0.22.2 // indirect
 	k8s.io/cli-runtime v0.22.2 // indirect
 	k8s.io/client-go v0.22.2 // indirect
+	k8s.io/cluster-bootstrap v0.22.2 // indirect
 	k8s.io/component-base v0.22.2 // indirect
-	k8s.io/klog/v2 v2.9.0 // indirect
-	k8s.io/kube-openapi v0.0.0-20210421082810-95288971da7e // indirect
+	k8s.io/klog/v2 v2.10.0 // indirect
+	k8s.io/kube-openapi v0.0.0-20210929172449-94abcedd1aa4 // indirect
 	k8s.io/utils v0.0.0-20210930125809-cb0fa318a74b // indirect
+	sigs.k8s.io/cluster-api v1.0.1 // indirect
+	sigs.k8s.io/cluster-api-provider-aws v1.0.0 // indirect
+	sigs.k8s.io/cluster-api-provider-azure v1.0.1 // indirect
+	sigs.k8s.io/cluster-api-provider-vsphere v1.0.2 // indirect
+	sigs.k8s.io/cluster-api/test v1.0.1 // indirect
 	sigs.k8s.io/controller-runtime v0.10.3 // indirect
 	sigs.k8s.io/structured-merge-diff/v4 v4.1.2 // indirect
 	sigs.k8s.io/yaml v1.3.0 // indirect
diff --git a/cli/cmd/plugin/diagnostics/go.sum b/cli/cmd/plugin/diagnostics/go.sum
index 6f574fd7..cd30cf80 100644
--- a/cli/cmd/plugin/diagnostics/go.sum
+++ b/cli/cmd/plugin/diagnostics/go.sum
...
...
gory details
...
...
diff --git a/hack/FRAMEWORK_BUILD_VERSION b/hack/FRAMEWORK_BUILD_VERSION
index 4b8f7b07..1417ff62 100644
--- a/hack/FRAMEWORK_BUILD_VERSION
+++ b/hack/FRAMEWORK_BUILD_VERSION
@@ -1 +1 @@
-v0.11.2
+v0.11.3
\ No newline at end of file
diff --git a/hack/builder/go.mod b/hack/builder/go.mod
index 70e141b9..47be3537 100644
--- a/hack/builder/go.mod
+++ b/hack/builder/go.mod
@@ -7,7 +7,7 @@ go 1.17
 
 require (
 	github.com/spf13/cobra v1.4.0
-	github.com/vmware-tanzu/tanzu-framework v0.11.2
+	github.com/vmware-tanzu/tanzu-framework v0.11.3
 )
 
 require (
diff --git a/hack/builder/go.sum b/hack/builder/go.sum
index 74d09d8f..ab985a1d 100644
--- a/hack/builder/go.sum
+++ b/hack/builder/go.sum
...
...
gory details
...
...
```

**Comment by dvonthenen** [comment]
Then installing TCE (ignore the BOM error for now because it doesn't exist in the prod harbor repo):
```
[vonthd@rocky8 community-edition]$ ./release/tce-linux-amd64-v0.12.0-dev.1/install.sh 
+ set +x
====================================
 Installing Tanzu Community Edition
====================================

Installing tanzu cli to /usr/local/bin/tanzu
[sudo] password for vonthd: 
Sorry, try again.
[sudo] password for vonthd: 

Installing plugin 'builder:v0.11.3'
✔  successfully installed 'builder' plugin
Installing plugin 'codegen:v0.11.3'
✔  successfully installed 'codegen' plugin
Installing plugin 'cluster:v0.11.3'
✔  successfully installed 'cluster' plugin
Installing plugin 'kubernetes-release:v0.11.3'
✔  successfully installed 'kubernetes-release' plugin
Installing plugin 'login:v0.11.3'
✔  successfully installed 'login' plugin
Installing plugin 'management-cluster:v0.11.3'
Warning: Failed to initialize plugin '"management-cluster"' after installation. Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download default bom files from the registry: unable to get the default BOM file ImagePath and Image Tag from the TKG Compatibility file: unable to find the supported TKG BOM version for the management plugin version "v0.11.3" in the TKG Compatibility file "/home/vonthd/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml"
✔  successfully installed 'management-cluster' plugin
Installing plugin 'package:v0.11.3'
✔  successfully installed 'package' plugin
Installing plugin 'pinniped-auth:v0.11.3'
✔  successfully installed 'pinniped-auth' plugin
Installing plugin 'secret:v0.11.3'
✔  successfully installed 'secret' plugin
Installing plugin 'conformance:v0.12.0-dev.1'
✔  successfully installed 'conformance' plugin
Installing plugin 'diagnostics:v0.12.0-dev.1'
✔  successfully installed 'diagnostics' plugin
Installing plugin 'unmanaged-cluster:v0.12.0-dev.1'
✔  successfully installed 'unmanaged-cluster' plugin

Installation complete!
```

**Comment by dvonthenen** [comment]
Will create a subsequent PR which actually bumps the TF version to `v0.11.3`. I want to keep the PR for the mechanism to this separate from the actual bump of the version.

**Review by stmcginnis — APPROVED** [review]
Running `make release` as-is right now would result in modified `diagnostic` files since that `go.mod` still points to the t-f v0.10 release. But since there will be a follow up shortly after this to move to the more recent t-f, that will go away soon.

Checked this out locally. Edited `hack/FRAMEWORK_BUILD_VERSION` to contain v0.11.1, then ran `make release ENVS=linux-amd64`. Build was successful, with the few modified go.[mod|sum] files. Installed the resulting build and created and deleted an unmanaged cluster. Everything looks good.

```
$ tanzu version
version: v0.11.1
buildDate: 2022-04-05
sha: 20e50da
```

**Review by jpmcb — APPROVED** [review]
Ran the following workflow:

```
❯ make clean
rm -rf ./release
rm -f ./hack/NEW_BUILD_VERSION
rm -rf ./artifacts
rm -rf ./build
rm -rf /tmp/tce-scratch-space
rm -rf /home/jmcb/.local/share/tanzu-cli
rm -rf /home/jmcb/.config/tanzu
rm -rf /home/jmcb/.config/tanzu-plugins
rm -rf /home/jmcb/.cache/tanzu
mkdir -p /home/jmcb/.local/share/tanzu-cli
mkdir -p /home/jmcb/.config/tanzu
mkdir -p /home/jmcb/.config/tanzu-plugins
mkdir -p /home/jmcb/.cache/tanzu

❯ ./hack/release/uninstall.sh
+ set +x
======================================
 Uninstalling Tanzu Community Edition
======================================

Uninstall complete!

❯ cat hack/FRAMEWORK_BUILD_VERSION
v0.11.2
❯ echo "v0.11.4" | tee ./hack/FRAMEWORK_BUILD_VERSION
v0.11.4
❯ cat hack/FRAMEWORK_BUILD_VERSION
v0.11.4
❯ make release
...

❯ pwd
/home/jmcb/workspace/github.com/vmware-tanzu/tce/release/tce-linux-amd64-v0.12.0-dev.1

❯ ./install.sh
+ set +x
====================================
 Installing Tanzu Community Edition
====================================

Installing tanzu cli to /usr/local/bin/tanzu
[sudo] password for jmcb:

Installing plugin 'builder:v0.11.4'
✔  successfully installed 'builder' plugin
Installing plugin 'codegen:v0.11.4'
✔  successfully installed 'codegen' plugin
Installing plugin 'cluster:v0.11.4'
✔  successfully installed 'cluster' plugin
Installing plugin 'kubernetes-release:v0.11.4'
✔  successfully installed 'kubernetes-release' plugin
Installing plugin 'login:v0.11.4'
✔  successfully installed 'login' plugin
Installing plugin 'management-cluster:v0.11.4'
Warning: Failed to initialize plugin '"management-cluster"' after installation. Downloading TKG compatibility file from 'projects.registry.vmware.com/tkg/framework-zshippable/tkg-compatibility'
Error: unable to ensure prerequisites: unable to ensure tkg BOM file: failed to download default bom files from the registry: unable to get the default BOM file ImagePath and Image Tag from the TKG Compatibility file: unable to find the supported TKG BOM version for the management plugin version "v0.11.4" in the TKG Compatibility file "/home/jmcb/.config/tanzu/tkg/compatibility/tkg-compatibility.yaml"
✔  successfully installed 'management-cluster' plugin
Installing plugin 'package:v0.11.4'
✔  successfully installed 'package' plugin
Installing plugin 'pinniped-auth:v0.11.4'
✔  successfully installed 'pinniped-auth' plugin
Installing plugin 'secret:v0.11.4'
✔  successfully installed 'secret' plugin
Installing plugin 'conformance:v0.12.0-dev.1'
✔  successfully installed 'conformance' plugin
Installing plugin 'diagnostics:v0.12.0-dev.1'
✔  successfully installed 'diagnostics' plugin
Installing plugin 'unmanaged-cluster:v0.12.0-dev.1'
✔  successfully installed 'unmanaged-cluster' plugin

Installation complete!

❯ tanzu version
version: v0.11.4
buildDate: 2022-04-06
sha: a9b8f3a
```

Nice! 👍🏼

**Pull request merged**
