### PR TITLE
Update package-management.md

### PR DESCRIPTION
**Pull request by rsimpson-cb**
Fix typo!

## What this PR does / why we need it

Fix typo

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
None
```

## Which issue(s) this PR fixes

Fixes: #

### CODE REVIEW

**Review by seemiller — APPROVED** [review]

**Comment by seemiller** [comment]
@rsimpson-cb Are you able to sign the CLA?

**Comment by rsimpson-cb** [comment]
I work at vmw, so do I still have to sign it?

**Comment by dvonthenen** [comment]
> I work at vmw, so do I still have to sign it?

The easy route would be to sign since it's blocking the merge

**Comment by stmcginnis** [comment]
Make sure you follow the instructions the bot references. It is a simple process for employees:

> If you are a VMware employee, read [this](https://cla.vmware.com/employee) for further instruction.

**Pull request closed without merging**
