### PR TITLE
fix out of date external-dns v0.10.0 go sum

### PR DESCRIPTION
**Pull request by joshrosso**
Fixes stale go.sum causing automation to fail.

### CODE REVIEW

**Comment by joshrosso** [comment]
cc @vmware-tanzu/pkg-external-dns-owners

**Comment by stmcginnis** [comment]
Hmm, looks like something missing yet:
```
Error: /home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.16.4/ginkgo/bootstrap_command.go:15:2: missing go.sum entry for module providing package github.com/go-task/slim-sprig (imported by github.com/onsi/ginkgo/ginkgo); to add:
	go get github.com/onsi/ginkgo/ginkgo@v1.16.4
Error: /home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.16.4/ginkgo/outline/outline.go:10:2: missing go.sum entry for module providing package golang.org/x/tools/go/ast/inspector (imported by github.com/onsi/ginkgo/ginkgo/outline); to add:
	go get github.com/onsi/ginkgo/ginkgo/outline@v1.16.4
```

**Comment by joshrosso** [comment]
@stmcginnis those are end to end tests owned by @vmware-tanzu/pkg-external-dns-owners. Would look for their consult.

Due to not having a tidy go sum, our post-merge stuff is breaking.

**Comment by christianang** [comment]
Yeah, our team will look into it a bit more. I've also tried updating go mod's in this PR: #2963 as well, which I think may fix it, but the lint is still telling me I need to run `go mod tidy`, which is odd.

Looks like @dvonthenen also disabled the tests for now, so it looks it shouldn't block anything at the moment.

**Comment by christianang** [comment]
Actually, I think I now realize the issue. Ginkgo needs to be imported into the test package for the Makefile to run `go run github.com/onsi/ginkgo/ginkgo`. This is so the go.sum could have the right dependencies otherwise the `go run` would complain. I think this was done at some point by manually running `go get` on our machine, but would end up being removed by `go mod tidy` later. Adding that to #2963 and once that is merged I think this issue will go away.

**Comment by dvonthenen** [comment]
@christianang I approved and merged https://github.com/vmware-tanzu/community-edition/pull/2963

If it looks like it's been fixed, can you close this PR out? Thanks!

**Comment by christianang** [comment]
Seeing checks pass on: #3031 after a rebase, so I'll close this out.

**Pull request closed without merging**
