### PR TITLE
Remove left versioned annotations in the CSI && CPI && Calico

### PR DESCRIPTION
**Pull request by chenliu1993**
## What this PR does / why we need it

Remove all versioned annotations in the CSI and CPI and Calico

## Which issue(s) this PR fixes

Fixes: # ..., some issues may be caused by versioned renaming.

## Describe testing done for PR

1. ytt will generate the template without versioned
2. test on the tce workload cluster's running status
## Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Review by nicolehanjing — COMMENTED** [review]
cpi part looks good to me

**Review by andrewsykim — COMMENTED** [review]
minor questions LGTM!

**Review by nicolehanjing — APPROVED** [review]
LGTM

**Review by tylerschultz — APPROVED** [review]
LGTM for the changes to remove the calico package annotations

As y'all have pointed out, package version process and procedures are unclear.

**Pull request merged**
