### PR TITLE
Add cert-injection-webhook package

### LINKED ISSUE #2689: Proposal to add Cert Injection Webhook as a Tanzu package in the TCE Package Repo
## Feature Request

The [cert injection webhook](https://github.com/vmware-tanzu/cert-injection-webhook) is a controller and webhook configuration that can inject trusted ca certificates into pods that need to communicate with services that have self signed certificates. It can be used with other deployments like kpack to allow builds to push images to self signed registries. The addition of the cert injection webhook package would allow kpack to leverage it, but its consumption wouldn't  have to just be limited to kpack. There is another proposal (#2462 ) to add kpack to TCE.

## Describe alternatives you've considered

One alternative would be to include the cert injection webhook as part of the kpack package. We decided against this because there may be cases where you don't have kpack installed, but want to leverage the cert injection webhook, such as a cluster that is running application workloads that communicate with a self signed service. Alternatively, If a user doesn't have a need for self signed cert support, they do not have to deploy an additional controller.

## Additional context

kpack proposal - #2462

### PR DESCRIPTION
**Pull request by tomkennedy513**
## What this PR does / why we need it
This PR adds the [Cert Injection Webhook](https://github.com/vmware-tanzu/cert-injection-webhook) as an installable package

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Add Cert Injection Webhook v0.1.0 as an installable package
```

## Which issue(s) this PR fixes

Fixes: #2689 

## Describe testing done for PR
Ran smoke tests against deployed package

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
Does this package inject a certificate or a CA? If the latter, maybe name should be revisited. If the former, is there a way then to integrate with cert-manager so that if the cluster has cert-manager configured with a CAIssuer this is used?

**Comment by jorgemoralespou** [comment]
I would also recommend to update the README and package metadata longDescription to give a bit more context on why this is needed, as currently it seems it's only for kpack. Is that the case? Why does kpack require the CAcert to be injected into the pod? Can't it use the CAcert chain that is on the node?

**Comment by jorgemoralespou** [comment]
I've been looking at this package, and it would be nice to integrate it with cert-manager.

This cert-injection-webhook expects that the user provides the ca_cert_data. For platforms where [cert-manager](https://cert-manager.io/) is installed, a user could potentially have a SelfSigned cluster issuer (or really any Issuer) and would want to reuse the CA in those, instead of manually copying from place to place. For that, cert-manager provides a [CA injector](https://cert-manager.io/docs/concepts/ca-injector/) that injects the CA in webhooks, this way, a user could deploy cert-injection-webhook with a reference to the cert-manager's Issuer, which is something that can be easier for end users.

This would give a config like:
```
useCertManager: true
issuer:
  namespace: example
  name: selfsignedissuer
ca_cert_data: <NOTHING>
...
```

**Comment by tomkennedy513** [comment]
> Why does kpack require the CAcert to be injected into the pod? Can't it use the CAcert chain that is on the node? 

kpack would require the CA cert to talk to registry that is using a self signed certificate which we see happen a lot. We could theoretically mount the certs from the node, but it's unclear to me exactly what that would look like. Additionally, I'm not sure we would expect the registry cert to exist on the node for the kpack use case.

**Comment by tomkennedy513** [comment]
> I've been looking at this package, and it would be nice to integrate it with cert-manager.
> 
> This cert-injection-webhook expects that the user provides the ca_cert_data. For platforms where [cert-manager](https://cert-manager.io/) is installed, a user could potentially have a SelfSigned cluster issuer (or really any Issuer) and would want to reuse the CA in those, instead of manually copying from place to place. For that, cert-manager provides a [CA injector](https://cert-manager.io/docs/concepts/ca-injector/) that injects the CA in webhooks, this way, a user could deploy cert-injection-webhook with a reference to the cert-manager's Issuer, which is something that can be easier for end users.
> 
> This would give a config like:
> 
> ```
> useCertManager: true
> issuer:
>   namespace: example
>   name: selfsignedissuer
> ca_cert_data: <NOTHING>
> ...
> ```

This is definitely something that could be nice to add in the future. It would likely not be applicable in the kpack use case because we usually see those registries deployed off cluster so the cert would not be generated by cert-manager, but this might be valuable for other types of workloads. Would you be open to creating an issue in the repo for this?

**Comment by jorgemoralespou** [comment]
> Would you be open to creating an issue in the repo for this?

@tomkennedy513 should this be in the cert-injection-webhook repo or in the package repo?

**Comment by tomkennedy513** [comment]
> > Would you be open to creating an issue in the repo for this?
> 
> @tomkennedy513 should this be in the cert-injection-webhook repo or in the package repo?

We actually don't have a separate repo for the webhook package so https://github.com/vmware-tanzu/cert-injection-webhook is perfect

**Review by seemiller — CHANGES_REQUESTED** [review]
@tomkennedy513 Could you remove the `addons/repos/main.yaml` file from the PR? We will make this change when we are ready to publish the package in in our package repository.

**Comment by tomkennedy513** [comment]
> @tomkennedy513 Could you remove the `addons/repos/main.yaml` file from the PR? We will make this change when we are ready to publish the package in in our package repository.

@seemiller done

**Review by seemiller — APPROVED** [review]

**Pull request merged**
