### PR TITLE
Fix preview for edge and local

### LINKED ISSUE #4059: Doc preview updates not showing in edge
When I create a PR with doc edits, I can’t see edits to existing files in edge preview and  new file shows in toc, but gives a link error.
ref: #https://github.com/vmware-tanzu/community-edition/pull/4058

## Expected Behavior
I expect to see updates to existing file and new file

## Steps to Reproduce the Bug

- I create a PR, edit an existing file and add another new file https://github.com/vmware-tanzu/community-edition/pull/4058
- I click on the netlify preview link in the PR, select the Documentation tab and change the url from docs/v0.11/ to docs/edge
- updates to existing file not showing, new file showing in toc, but link broken

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Unmanaged cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):

### PR DESCRIPTION
**Pull request by a-mccarthy**
## What this PR does / why we need it
This PR addresses the issues in viewing docs changes locally and in deploy previews. Essentially, the current setup does not align with how hugo expects content to be available to build local previews  or PR previews and how we have the website set up to handle versioning. 

To address this issue, this PR 
* Moves docs files from` content/docs` to `content/docs/edge`
* updates the load-docs.sh script to account for the new file location of the docs 

This will update docs processes slightly, so that content will now need to be updated in the `content/docs/edge` folder.

Currently this PR also has an example file changed /content/docs/edge/architecture.md, to show how a file will look when making a PR.

deploy preview link - https://deploy-preview-4235--quirky-franklin-8969be.netlify.app/docs/edge/architecture/

If we decide that this approach is something we'd like to do, we'd have to:
- [ ] Update each release branch to move docs into a `content/docs/edge`
- [x] Remove changes in content/docs/edge/architecture.md before merging (its only here as an example)
- [ ] Make sure all out docs on docs are up to date with the new folder scheme/process
- [x] Abbie needs to do some PR clean-up for the merge conflict and signing the dco :) 

## Which issue(s) this PR fixes

Fixes: #4059  and also #3687 i think

## Describe testing done for PR
I tested it locally and it seemed to work, as well as when i opened the PR, the deploy preview loaded correctly.

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@jonasrosland and @kcoriordan made this PR to hopefully address the issues with the local and PR previews of the site.

**Comment by kcoriordan** [comment]
Thank @a-mccarthy the preview link worked for me:
https://deploy-preview-4235--quirky-franklin-8969be.netlify.app/docs/edge/architecture/

**Review by kcoriordan — DISMISSED** [review]

**Comment by jonasrosland** [comment]
LGTM, this will resolve issues we have with PR previews not working, and also enable easier local previews as well.

**Comment by a-mccarthy** [comment]
closing this in favor of https://github.com/vmware-tanzu/community-edition/pull/4319

**Pull request closed without merging**
