### PR TITLE
Removal of standalone support mode in Diagnostics plugin

### LINKED ISSUE #2864: Remove `standalone-cluster` diagnostics collection in `v0.11.0`
In support of deprecating `standalone-clusters` and introducing `unamanged-clusters`, we should remove `standalone-cluster` support from the `diagnostics` plugin and, if possible, introduce the ability to get diagnostics for `unmanaged-clusters`

Related to https://github.com/vmware-tanzu/community-edition/issues/2266 and https://github.com/vmware-tanzu/community-edition/issues/2705

cc @vladimirvivien - If you don't have any bandwidth to take this on, I think one of us working on the `standalone-cluster` / `unmanaged-cluster` would be happy to at least remove the `standalone-cluster` support. The `unmanaged-cluster` is going into a sort of "alpha" state, so the need for diagnostics collection isn't immediate right now.

---

Note: issue created to track adding diagnostics support for `unmanaged-clusters`
- https://github.com/vmware-tanzu/community-edition/issues/2936

### PR DESCRIPTION
**Pull request by vladimirvivien**
## What this PR does / why we need it
This PR removes reference to `standalone-cluster` as it is being phased out.

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
Diagnostics plugin does removes support for stand-alone cluster
```

## Which issue(s) this PR fixes

Fixes: #2864 

## Describe testing done for PR
Run the plugins e2e test suite

## Special notes for your reviewer
This PR simply deprecate reference to the old standalone cluster. It does not provide support for the new unmanaged cluster mode.  As mentioned in #2864 , that feature is alpha and true support can come later.

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
This is looking good to me!

Will also let @vmware-tanzu/tce-releng take a look since this touches some of the e2e tests

**Comment by nrb** [comment]
@vladimirvivien Are you planning to open a second PR that adds these checks to the newer `unmanaged` implementation?

`standalone` is deprecated and will be going away, but it will not be totally gone in v0.10.0.

**Comment by vladimirvivien** [comment]
@nrb @jpmcb 
Going by comment in original issue, it sounds like the unmanaged is going to be alpha and support not needed right away. I will open an issue, but I don't have bandwidth to address for v0.10.0 (which I think is slated soon).

**Comment by vladimirvivien** [comment]
https://github.com/vmware-tanzu/community-edition/issues/2936

**Comment by nrb** [comment]
@vladimirvivien Thanks!

**Review by karuppiah7890 — APPROVED** [review]
LGTM ! 😄

**Comment by karuppiah7890** [comment]
Diagnostics plugin will still have support for `standalone-cluster` in TCE v0.10.0 too right? As in, even if this gets merged to `main`, this commit won't be released as part of TCE v0.10.0 right? I'm asking this because in TCE v0.11.0 only `standalone-cluster` gets removed

**Comment by vladimirvivien** [comment]
@karuppiah7890 
if this gets merged to `main` all references to `standalone-cluster` will be removed.
If `v0.10.0` has not been cut, then this should be delayed until after.

**Review by jpmcb — CHANGES_REQUESTED** [review]
🛑 Hold until after v0.10.0 releases so that we can coordinate the deprecation of standalone-cluster with it's diagnostics capabilities being removed

**Review by jpmcb — APPROVED** [review]
Re-targetd this against the `next` branch which contains the other `standalone-cluster` removal commits - This LGTM 🚀

**Pull request merged**
