### PR TITLE
Get avi secrets name from overlay values file in kapp-config for ako-…

### PR DESCRIPTION
**Pull request by sbhatp**
…operator

Signed-off-by: Sharath Bhat <sharathb@vmware.com>

## Which issue(s) this PR fixes

Fixes: #

### CODE REVIEW

**Comment by HanFa** [comment]
let's added a test for this

```
	Context("kapp rebase rule for credentials and CA", func() {
		When("avi_admin_credential_name and avi_ca_name is specified", func() {
			BeforeEach(func() {
				values = defaultValues  + "\n" + "  config:\n" + "    avi_admin_credential_name: avi-controller-credentials\n" + "    avi_ca_name: avi-controller-ca"
			})
			It("should have rebase rule to skip their reconcilation in kapp-config", func() {
				cms, err := matchers.FindDocsMatchingYAMLPath(output, map[string]string{
					"$.kind": "ConfigMap",
					"$.metadata.name": "ako-operator-kapp-config",
				})
				Expect(err).NotTo(HaveOccurred())
				Expect(cms).To(HaveLen(1))

				Expect(cms[0]).To(ContainSubstring("[data, username]"))
				Expect(cms[0]).To(ContainSubstring("[data, password]"))
				Expect(cms[0]).To(ContainSubstring("[data, certificateAuthorityData]"))
			})
		})
	})
```

**Comment by sbhatp** [comment]
> let's add a test for this
> 
> ```
> 	Context("kapp rebase rule for credentials and CA", func() {
> 		When("avi_admin_credential_name and avi_ca_name is specified", func() {
> 			BeforeEach(func() {
> 				values = defaultValues  + "\n" + "  config:\n" + "    avi_admin_credential_name: avi-controller-credentials\n" + "    avi_ca_name: avi-controller-ca"
> 			})
> 			It("should have rebase rule to skip their reconcilation in kapp-config", func() {
> 				cms, err := matchers.FindDocsMatchingYAMLPath(output, map[string]string{
> 					"$.kind": "ConfigMap",
> 					"$.metadata.name": "ako-operator-kapp-config",
> 				})
> 				Expect(err).NotTo(HaveOccurred())
> 				Expect(cms).To(HaveLen(1))
> 
> 				Expect(cms[0]).To(ContainSubstring("[data, username]"))
> 				Expect(cms[0]).To(ContainSubstring("[data, password]"))
> 				Expect(cms[0]).To(ContainSubstring("[data, certificateAuthorityData]"))
> 			})
> 		})
> 	})
> ```

Sure, thanks

**Review by lubronzhan — APPROVED** [review]
lgtm

**Review by XudongLiuHarold — APPROVED** [review]
Thanks!

**Pull request merged**
