### PR TITLE
Added e2e test for whereabouts package

### LINKED ISSUE #2672: Add e2e test for whereabouts package
## Feature Request

Add e2e test for whereabouts package https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/whereabouts

## Describe alternatives you've considered

- [x] e2e test case

### PR DESCRIPTION
**Pull request by zhanggbj**
Added e2e test for whereabouts package to test package install and delete and pod secondary
interface creation.

[issue 2672](https://github.com/vmware-tanzu/community-edition/issues/2672)

## Details for the Release Notes (PLEASE PROVIDE)

```release-note
Added e2e test for whereabouts package
```

## Which issue(s) this PR fixes

Fixes: #2672

### CODE REVIEW

**Review by chenliu1993 — APPROVED** [review]
Maybe whereabouts also needs to remove the leftover multus files like the issue multus-cni currently met. Other parts LGTM!

**Comment by zhanggbj** [comment]
test result
```
• [SLOW TEST:281.699 seconds]
Whereabouts Addon E2E Test
/Users/zgong/zhanggong/tanzu/dev/src/github.com/vmware-tanzu/community-edition/addons/packages/whereabouts/0.5.0/test/e2e/whereabouts_test.go:24
  Check Pod secondary interface
  /Users/zgong/zhanggong/tanzu/dev/src/github.com/vmware-tanzu/community-edition/addons/packages/whereabouts/0.5.0/test/e2e/whereabouts_test.go:110
------------------------------

Ran 1 of 1 Specs in 307.322 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 5m20.170064902s
Test Suite Passed
```

**Comment by zhanggbj** [comment]
@chenliu1993 it make sense, would you please help to link the multus issue here?

**Comment by chenliu1993** [comment]
> @chenliu1993 it make sense, would you please help to link the multus issue here?

It is https://github.com/vmware-tanzu/community-edition/issues/2595

**Comment by dvonthenen** [comment]
based on the previous comment, I will defer to subject experts... if would want to:

- wait for an update to address issues
OR
- just merge and have a subsequent follow up PR to address the issues
- 
Please let me know.

**Comment by zhanggbj** [comment]
For me, I prefer to wait for #2595 merged and update this PR, since it has some dependency. Thanks!

**Comment by dvonthenen** [comment]
PR https://github.com/vmware-tanzu/community-edition/pull/2728 has been merged

**Review by davidvonthenen — APPROVED** [review]
deferring to subject matter experts

**Pull request merged**
