### PR TITLE
Add missing fields to CPI schema

### PR DESCRIPTION
**Pull request by lubronzhan**
## What this PR does / why we need it

The CPI `schema.yaml`  is missing two important fields.
Correct the sample-values folder's location

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #

### CODE REVIEW

**Review by HanFa — COMMENTED** [review]
have you rerun `make generate-openapischema-package PACKAGE=vsphere-cpi VERSION=1.22.5` to regenerate from the schema file?

**Comment by lubronzhan** [comment]
No, is this some new requirement?

**Comment by lubronzhan** [comment]
Ok I ran the command again

**Comment by HanFa** [comment]
/lgtm
thanks @lubronzhan

**Review by HanFa — APPROVED** [review]

**Comment by tylerschultz** [comment]
LGTM - sorry we missed this on the first review

**Pull request merged**
