### PR TITLE
Add contour.ipv6Enabled option for Contour package

### LINKED ISSUE #4324: Contour package field to enable ipv6 (for Contour xDS server listeners/addresses and Envoy listeners/addresses)
## Feature Request
The Contour package should enable users to opt in to deploying Contour with ipv6 cluster compatible flags for listener addresses etc. This includes addresses for Contour and Envoy (e.g. flags like `--xds-address` and `--envoy-service-http-address` in the Contour Deployment). Ideally this would be a single value to configure, e.g. `contour.listenerIpFamily` or something similar.

## Describe alternatives you've considered
- Make users manually set flags for listen addresses etc.? Not really a good experience

## Additional context
The [cluster configuration](https://projectcontour.io/docs/v1.20.1/configuration/#cluster-configuration) has a field for lookup family used for ExternalName services, we may have to add a caveat to the documentation that if you're using an ipv6 only cluster, you should make sure to set this appropriately as well. It is a lone field in the embedded YAML of the values, so not sure if we can override it?

cc @vmware-tanzu/contour-owners @vmware-tanzu/pkg-contour-owners

### PR DESCRIPTION
**Pull request by sunjayBhatia**
## What this PR does / why we need it
Adds boolean option to enable user to opt into setting Contour and Envoy to
listen on IPv6 addresses.

To ensure IPv6 and dual-stack cluster compatibility with Contour package.

## Which issue(s) this PR fixes
Fixes: #4324

## Describe testing done for PR
WIP, so far added unit testing for overlay changes.

## Special notes for your reviewer
N/A

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Still TODO/discuss: The Contour ConfigMap/file based configuration mechanism allows specifying some addresses, specifically the metrics server addresses for Contour and Envoy (https://projectcontour.io/docs/v1.21.0/configuration/#metrics-server-parameters)

- Should we attempt to reach into the passed in config file value and error if the configured values conflict with the `ipv6Enabled` setting?
- Do the above but just warn somehow, since the CLI flags will override the config file?
- Ignore the config file and just document that the `ipv6Enabled` setting will override the config file? (easiest solution)

**Comment by sunjayBhatia** [comment]
Having permission issues pushing the updated package bundle, but other than that, should be good to review

**Comment by skriss** [comment]
Looks good to me, just need the package pushed / SHA updated

**Comment by skriss** [comment]
> Still TODO/discuss: The Contour ConfigMap/file based configuration mechanism allows specifying some addresses, specifically the metrics server addresses for Contour and Envoy (https://projectcontour.io/docs/v1.21.0/configuration/#metrics-server-parameters)
> 
> * Should we attempt to reach into the passed in config file value and error if the configured values conflict with the `ipv6Enabled` setting?
> * Do the above but just warn somehow, since the CLI flags will override the config file?
> * Ignore the config file and just document that the `ipv6Enabled` setting will override the config file? (easiest solution)

I'm comfortable with the third option to start since we currently treat the contour config as opaque YAML. Can always iterate if/when needed.

**Comment by sunjayBhatia** [comment]
closing in favor of #4804 and the solution that just resets contour/envoy listen addresses *always* to ipv6 w/ ipv4 compatibility

**Pull request closed without merging**
