### PR TITLE
Doc - Add missing step to Secure Automated Ingress on AWS topic

### LINKED ISSUE #2137: Error when installing ingress?
**On Page:** [](/docs/latest/solutions-secure-ingress/)

When trying to install the ingress controller as part of step 3, I get the following:

```
➜  devTools tanzu package available get contour.community.tanzu.vmware.com
- Retrieving package details for contour.community.tanzu.vmware.com...
package 'contour.community.tanzu.vmware.com' does not exist in namespace 'default'
```

This is different than is what is in the docs. I thought I followed the instructions exactly.

### PR DESCRIPTION
**Pull request by kcoriordan**
Signed-off-by: kcoriordan <koriordan@vmware.com>

## What this PR does / why we need it
-Adds missing step to install the TCE pkg repo in  [Secure automated Ingress on AWS](https://tanzucommunityedition.io/docs/latest/solutions-secure-ingress/#3-ingress-controller) topic (line 115) fixes #2137 
-Adds step numbering to same section of doc
-Other minor editorial updates
-changed the readme links to point to the docs site

## Details for the Release Notes (PLEASE PROVIDE)

```release-note

```

## Which issue(s) this PR fixes

Fixes: #2137

### CODE REVIEW

**Comment by kcoriordan** [comment]
@mikegehard @jorgemoralespou

**Comment by jorgemoralespou** [comment]
@kcoriordan Looks good to me, but since you are updating the package repository to latest, and show the new contour versions on the list, it feels weird that the guide installs an old version 1.17.1 instead than the latest one 1.19.1.
I think it should still work the same.

Also, once 1.20+ of contour package is out, this guide should be updated to reflect that now Ingressv1 can be used.

**Comment by kcoriordan** [comment]
OK - thanks @jorgemoralespou, I've updated the version now,   think this is ready to merge now
are you opening an issue for this: 
>Also, once 1.20+ of contour package is out, this guide should be updated to reflect that now Ingressv1 can be used.

**Comment by jorgemoralespou** [comment]
@kcoriordan https://github.com/vmware-tanzu/community-edition/issues/3159

**Review by jpmcb — APPROVED** [review]
LGTM - but will defer to @jorgemoralespou for a final approval 👍🏼

**Comment by jorgemoralespou** [comment]
@kcoriordan LGTM

**Pull request merged**
