### PR TITLE
[release-0.12] Update doc links to "edge" instead of "main" (#4323)

### PR DESCRIPTION
**Pull request by stmcginnis**
## What this PR does / why we need it

With recent changes in the versioned docs to allow seeing locally made
changes, the "main" version of the docs are no longer published and
there is just "edge". We had a few links in our README and CONTRIBUTING
docs that referenced other documentation under this path that now fail.

This updates those links to point to their "edge" equivalents.

(cherry picked from commit e57a466b3c1555cbf3756ab3c957b44f17a4b479)

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]

**Comment by jpmcb** [comment]
Does this need to go first? https://github.com/vmware-tanzu/community-edition/pull/4370

**Comment by stmcginnis** [comment]
No, since this references our edge ("main") location, we should get this merged before #4370

**Comment by jpmcb** [comment]
cc @vmware-tanzu/tce-owners - need second reviewer

**Comment by jpmcb** [comment]
@stmcginnis - these good to go now that we have the `edge` PRs merged?

**Comment by stmcginnis** [comment]
Yep, ready whenever you are. Will also watch for any other changes we need to backport to get everything happy.

**Pull request merged**
