### PR TITLE
Proposal to add Kubeapps to package addons.

### LINKED ISSUE #3732: Include Kubeapps in the TCE Repository
## Proposal

Include the [Kubeapps application](https://github.com/kubeapps/kubeapps) in the TCE repository so that users can view and interact with the packages available in the TCE repository via the Kubeapps UI, which now supports browsing and installing Carvel packages.

This requires ensuring that the [Carvel source package for the latest stable release of Kubeapps is available in a git repository](https://github.com/vmware-tanzu/community-edition/blob/main/docs/packaging/considerations/git.md).

In addition, once Kubeapps is installed, users would be able to enable the helm support and add the Bitnami application catalog to then be able to view and install both Carvel packages from the TCE repo as well as Helm packages from the Bitnami catalog.

Note: this proposal originated as #2418, but that proposal mixed two separate proposals: (1) adding Kubeapps to TCE and (2) adding the Bitnami Application Catalog as Carvel packages to TCE. This proposal focuses on the (1) only.

## Background

Kubeapps now supports Carvel packages (and Flux packages) in addition to Helm packages, so can be used to provide a visual catalog of the TCE repository to TCE users:

kubeapps-tce

Or with the Helm support enabled (and the Bitnami Helm app repository) so that both Helm and Carvel packages can be viewed:

kubeapps-carvel-helm

## Questions

While looking at the options for packaging Kubeapps as a Carvel package recently (including using a carvel package generated internally by the Bitnami Application Catalog), there have been a couple of questions/uncertainties from my side.

### 1. Admin access required for service account used with Carvel `PackageInstall`

Similar to a number of other packages already in the TCE repository, the Kubeapps package includes a CRD with a corresponding controller that runs as part of the install. This means that the service account used to reconcile a Carvel package with a CRD will need to have enough RBAC not only to create the CRD at the cluster-scope, but also to create a service account for the controller that services the CRD with the RBAC it requires to react to changes of a CR in *any* namespace. In the general case (as with some packages in the TCE repo), this appears to mean something akin to cluster-admin. In the Kubeapps-specific case, the cluster-wide RBAC required by the controller is limited to get/list on Kubeapps' own `AppRepository` custom resource (the controller doesn't generate other resources in the namespace of the `AppRepository`).  See the [slack conversation where I asked about this](https://kubernetes.slack.com/archives/CH8KCCKA5/p1648100519647849).

### 2. Carvel packaging using `helm-template`

Since Kubeapps is already part of the helm Bitnami Application Catalog (with security updates and lots of maintenance improvements handled by the Bitnami team), the path of least friction and most value for us would be to use the existing maintained Helm chart with the `helm-template` option for the carvel package. This option has been used in the past by @vrabbi as well as the Bitnami team and some tooling exists.

When I first looked at the Carvel packaging requirements, I saw that although Helm charts can be used as a [source for the upstream content](https://github.com/vmware-tanzu/community-edition/blob/main/docs/packaging/creation/upstream-content.md), the docs don't mention using the helm-template option for kapp to generate the template during the install (with user-supplied values). In fact, the other details for the packaging assume that the package always has the vendored yaml with ytt overlays etc.

But I [checked on slack](https://kubernetes.slack.com/archives/C02GY94A8KT/p1647826316652889) and the response was that it should be fine to use `helm-template`, it's just not documented yet because people haven't yet used that for TCE packages. 

### Kubeapps and Contour

Kubeapps currently has an issue when the Contour ingress controller is installed. In particular, Kubeapps can only be used with (service-account) token authentication when Contour is installed, until the Contour team [implement the ability to disable the currently automatic gRPC-web -> gRPC translation](https://github.com/projectcontour/contour/issues/4290).

Service-account token authentication is only recommended for demos, but OIDC auth for Kubeapps won't be possible currently unless the above Contour issue is resolved.

### Packaging versions and App versions

The Bitnami Kubeapps chart is updated regularly with fresher images for subcomponents or other packaging-only related changes, which creates a new chart version without changing the app version. Helm has the concept of separate package and app versions, where Carvel does not. We'll need to think about versioning carefully when translating automatic updates from the chart to the carvel package.

## High-level implementation path

I'll be seeing what I can re-use from the Bitnami team's Helm -> Carvel package translation to generate the carvel package source in a public github repository as per the [tce packaging docs](https://github.com/vmware-tanzu/community-edition/blob/main/docs/packaging/considerations/git.md). Other steps in the tce packaging doc requirements may not be relevant (lock container image references, add configurable params etc.) since they are already handled by the `helm-template`. Once we have a git repo with the package source,  we can test it for inclusion in the TCE repo and add our own CI for upgrades etc.

### PR DESCRIPTION
**Pull request by absoludity**
Signed-off-by: absoludity <absoludity@gmail.com>

## What this PR does / why we need it

Proposes adding the Kubeapps package to the community edition package addons.

## Which issue(s) this PR fixes

Fixes: #3732 

## Describe testing done for PR

The installation of the release is tested during the creation of the package release.

## Special notes for your reviewer

I've updated our release script to copy the README.md from the package-for-kubeapps repo, as it is the carvel-specific readme, but it currently is a little bit too specific to the package-for-kubeapps repo. Not sure if we'd be best to update the readme to be appropriate for the package, or create a separate readme with the bulk of that one (all the instructions for install etc.), or whether it's fine as is.

### CODE REVIEW

**Comment by absoludity** [comment]
> I'm updating the README.md to address the markdown lint, but will need to release a new version, which I'll do soon (just having issues with the bitnami helm repo atm).

...and done.

**Comment by ppbaena** [comment]
@vmware-tanzu/tce-owners this PR is just pending your approval. Let me know if we can help you in this process. Thanks!

**Review by seemiller — APPROVED** [review]
Looks good!

Here's a video of my test installation.

[asciicast](https://asciinema.org/a/uLdrIACTymSqbpPKTePs0mG3w)

Here are the steps:

- Create an unmanaged cluster for testing
    ```
    tanzu uc create kubeapp-cluster -p 127.0.0.1:80:80 -p 127.0.0.1:443:443
    ```

- add a package repository with Kubeapps
    ```
    tanzu package repository add kubeapps --url projects-stg.registry.vmware.com/tce/kubeapps@sha256:39c1cb23112b5258f9fc6f4554d80f67685a0e180f862c1b044a091fcfb3233d -n tanzu-package-repo-global
    ```
- Install the Kubeapps package
    ```
    tanzu package install kubeapps --package-name kubeapps.community.tanzu.vmware.com  --version 8.1.7
    ```
- Following steps at https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/tutorials/getting-started.md

- Create a service account
    ```
    kubectl create --namespace default serviceaccount kubeapps-operator
    ```

- Create a cluster role binding
    ```
    kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator
    ```

- Create a secret with a token
     ```
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Secret
    metadata:
      name: kubeapps-operator-token
      namespace: default
      annotations:
        kubernetes.io/service-account.name: kubeapps-operator
    type: kubernetes.io/service-account-token
    EOF
    ```

- Get the token

    ```
    kubectl get --namespace default secret kubeapps-operator-token -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo
    ```

- In another Terminal window
    ```
    kubectl port-forward svc/kubeapps 8080:80
    ```
- curl to see if it works
    ```
    curl 127.0.0.1:8080
    ```

**Comment by absoludity** [comment]
Thanks @seemiller !

**Pull request merged**
