### PR TITLE
Tanzu Diagnostics Plugin

### LINKED ISSUE #1335: Add `tanzu diagnostics` providing crashd support (cluster diagnostics)
## Feature Request

Add `tanzu diagnostics`, which will provide crashd integration so that cluster operators can get diagnostics on their clusters.

## Additional context

This work is being completed in tanzu-framework. After completion, this issue should be used to update our dependencies.

* https://github.com/vmware-tanzu/tanzu-framework/issues/297

### PR DESCRIPTION
**Pull request by vladimirvivien**
This patch introduces the start of the Tanzu Diagnostics plugin.
It uses the Crashd Go package to execute automation scripts to
collect cluster diagnostics.

Signed-off-by: Vladimir Vivien <vivienv@vmware.com>

## What this PR does / why we need it
This PR introduces the start of the Tanzu Diagnostics plugin.
It uses the Crashd Go package to execute automation scripts to
collect cluster diagnostics.

## Details for the Release Notes
```release-note
Tanzu Diagnostics Plugin: allows extraction of cluster diagnostics information
```

## Which issue(s) this PR fixes
Fixes: #1335

### CODE REVIEW

**Review by davidvonthenen — COMMENTED** [review]
hey @vladimirvivien !!

To make sure your binary ends up in the tarball, you want to include linux, darwin, and windows here:
https://github.com/vmware-tanzu/tce/blob/main/hack/package-release.sh

linux/darwin install should happen automatically, but windows needs to be updated ​here:
https://github.com/vmware-tanzu/tce/blob/main/hack/install.ba

**Review by nrb — COMMENTED** [review]
Aside from one stray letter, this looks like it's in great shape to me.

I did not look closely at the Starlark scripts, as I'm not really an expert there. The data that's been gathered looks accurate to me, though.

@dvonthenen or @jpmcb is the `package-release.sh` script the only thing that needs to be updated to ensure the binary lands in a release?

**Review by nrb — DISMISSED** [review]

**Review by davidvonthenen — COMMENTED** [review]
This looks great... the last thing we need to add is a copy for windows right after this line:
https://github.com/vmware-tanzu/community-edition/blob/main/hack/install.bat#L31

**Review by davidvonthenen — APPROVED** [review]
This is an awesome contribution! Merging!

**Pull request merged**
