### PR TITLE
Removes standalone-cluster plugin and all associated bits

### LINKED ISSUE #3005: Remove `standalone-cluster` in `v0.11.0`
In support of the new `unamanged-cluster` model, we are deprecating `standalone-cluster` in v0.11.0

Reference the following proposal in regards to implementing `unmanaged-cluster` and removing `standalone-cluster`: https://github.com/vmware-tanzu/community-edition/issues/2266

cc @qnetter

### PR DESCRIPTION
**Pull request by jpmcb**
## What this PR does / why we need it
- Removes standalone-cluster plugin
- Removes standalone-cluster e2e test for all providers: cc @vmware-tanzu/tce-releng 
- Removes standalone-cluster release and install

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
Remove core standalone-plugin, replaced by unmanaged-cluster
```

## Which issue(s) this PR fixes
Tracked by: #3005

## Describe testing done for PR

✅ 
```
make install-all-tanzu-cli-plugins
```

## Special notes for your reviewer

✅ targeting the `next` branch for v0.11.0

### CODE REVIEW

**Comment by jpmcb** [comment]
- [ ] Remove `standalone-cluster` bits in the hidden `.github` directory

**Comment by nrb** [comment]
Can you expand the release note to mention that this is being replaced by unmanaged-cluster? We probably can't say it enough times :)

**Comment by nrb** [comment]
👍 to the new note.

**Comment by joshrosso** [comment]
@jpmcb with the 0.16 additions, we created some merge conflicts. Would you mind cleaning these up and then we'll merge this in?

Thank you!

**Comment by jpmcb** [comment]
@joshrosso - done! 👍🏼

**Review by davidvonthenen — APPROVED** [review]

**Comment by dvonthenen** [comment]
LGTM

**Review by joshrosso — APPROVED** [review]
build still work great with no more standalone

```
./artifacts
├── conformance
│   ├── plugin.yaml
│   └── v0.10.0-dev.5
│       ├── tanzu-conformance-linux_amd64
│       └── test
│           └── tanzu-conformance-test-linux_amd64
├── diagnostics
│   ├── plugin.yaml
│   └── v0.10.0-dev.5
│       ├── tanzu-diagnostics-linux_amd64
│       └── test
│           └── tanzu-diagnostics-test-linux_amd64
├── manifest.yaml
└── unmanaged-cluster
    ├── plugin.yaml
    └── v0.10.0-dev.5
        ├── tanzu-unmanaged-cluster-linux_amd64
        └── test
            └── tanzu-unmanaged-cluster-test-linux_amd64
```

**Pull request merged**
