### PR TITLE
Solution Guide to secure ingress on AWS

### LINKED ISSUE #1559: Solution Doc for MVP
@gshipley @thesteve0 @jorgemoralespou are providing some TCE solution doc  for:
Tekton, PostgreSQL, iterative dev, Prometheus, where’s my logs?, CNR - for starters.
With a target of 9/17

### PR DESCRIPTION
**Pull request by jorgemoralespou**
## What this PR does / why we need it
This guide provides a solution guide that will guide you through the process of:
- deploying a sample application
- deploying an ingress controller via the contour package
- configuring external-dns with Route53 to generate domain names for you
- configure cert-manager integration with Let's Encrypt to get you a wildcard certificate for your domain to use with your apps
- demonstrate with the sample app everything is working

NOTE: The guide uses an image in a personal repository that should be moved to TCE somehow. Please advice on what is the best way before merging this PR. The application is a sample application that displays `Tanzu Community Edition` in asciiart format.

## Details for the Release Notes (PLEASE PROVIDE)
```release-note
Solution Guide for secure and automated ingress on AWS using packages
```

## Which issue(s) this PR fixes

Fixes: #1559

## Describe testing done for PR
hugo server on the docs/content folder

## Special notes for your reviewer
NOTE: The guide uses an image in a personal repository that should be moved to TCE somehow. Please advice on what is the best way before merging this PR. The application is a sample application that displays `Tanzu Community Edition` in asciiart format.

Signed-off-by: Jorge Morales Pou <jomorales@vmware.com>

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
Hi @jorgemoralespou - we very, _very_ recently enabled MD linting on the `docs/` directory

Ref PR: https://github.com/vmware-tanzu/community-edition/pull/1790

Would you be able to rebase and run the linter locally to fix those issues? Thanks much!

**Review by kcoriordan — DISMISSED** [review]

**Review by joshrosso — CHANGES_REQUESTED** [review]
@jorgemoralespou thanks for the great work on this PR!

Comments added.

**Review by jorgemoralespou — COMMENTED** [review]
Changes reviewed

**Review by joshrosso — DISMISSED** [review]
@jorgemoralespou as a final step, can you squash your commit into 1 descriptive commit message?

Thanks!

**Review by seemiller — APPROVED** [review]
LGTM

**Pull request merged**
