### PR TITLE
doc- Fix codeblock in clean-up.md to display missing line.

### LINKED ISSUE #2153: Doc -  missing management-cluster delete command in Getting Started Guide
## Description

Doc Formatting issue: 

For getting started, the management-cluster delete command is in the source, but is not showing up on the site.
https://tanzucommunityedition.io/docs/latest/getting-started/#cleaning-up

https://github.com/vmware-tanzu/community-edition/blob/main/docs/site/content/docs/assets/clean-up.md

### PR DESCRIPTION
**Pull request by kcoriordan**
Signed-off-by: kcoriordan <koriordan@vmware.com>

## What this PR does / why we need it
Removes extra space in code block so that missing line displays correctly.

## Details for the Release Notes (PLEASE PROVIDE)

```NONE

```

## Which issue(s) this PR fixes

Fixes: #2153 

## Describe testing done for PR
Run hugo server as per instructions in [readme](https://github.com/vmware-tanzu/community-edition/blob/main/docs/README.md)

### CODE REVIEW

**Comment by stmcginnis** [comment]
Something's odd here. This fixes it from the output, but it should have been fine how it was. There was another issue recently about how some of our preprocessing was messing up normal markdown rendering. I wonder if this is another instance of that.

**Comment by jpmcb** [comment]
> There was another issue recently about how some of our preprocessing was messing up normal markdown rendering

I think you're talking about this: https://github.com/vmware-tanzu/community-edition/pull/2047. I'm not sure what's going on or if this fully fixed the CSS rendering issue.

**Comment by stmcginnis** [comment]
Yep, that's the one @jpmcb! Looks like we may still have an issue there.

No reason to hold this up though. I'm just concerned there may be other places where things are getting cut from the output. We should definitely keep an eye on this.

**Review by stmcginnis — APPROVED** [review]

**Comment by kcoriordan** [comment]
thanks @stmcginnis will keep any eye out for any more occurrences like this

**Pull request merged**
